#!/usr/bin/env bash
# scan_lean_census.sh — bake the Lean corpus census into the kernel.
#
# The kernel is no_std with no filesystem: it cannot read *.lean at runtime.
# `redteam audit` and `provenance` read the table generated here. Regenerate
# after any Lean change; the table is dated so a stale census announces itself.
#
# Counts are PER THEOREM, not per file. A file-level count let one `by decide`
# on an arithmetic identity drag a genuine proof down with it — Crystal.lean
# graded COMPUTED although `crystal_roundtrip` is universally quantified and
# closed by omega, while only `crystal_total_size` used decide. Each theorem is
# now attributed to the tactic that actually closes IT.
#
#   ./scan_lean_census.sh   ->  src/lean_census.rs
set -euo pipefail
cd "$(dirname "$0")"
ROOT="${1:-..}"
OUT="src/lean_census.rs"
STAMP="$(date +%Y-%m-%d)"

python3 - "$ROOT" "$OUT" "$STAMP" <<'PY'
import os, re, sys
root, out, stamp = sys.argv[1], sys.argv[2], sys.argv[3]

DECL = re.compile(r'^\s*(?:@\[[^\]]*\]\s*)?(?:private\s+|protected\s+|noncomputable\s+|partial\s+)*'
                  r'(theorem|lemma|def|instance|structure|inductive|abbrev|axiom|example)\b')
TOP  = re.compile(r'^\S')

skip = ('/.lake/', '/build/', '/momonados-proof-', '/backup')
rows = []
for dirpath, dirnames, filenames in os.walk(root):
    if any(s in dirpath.replace(os.sep, '/') + '/' for s in skip):
        dirnames[:] = []
        continue
    for fn in filenames:
        if not fn.endswith('.lean'):
            continue
        path = os.path.join(dirpath, fn)
        rel = os.path.relpath(path, root).replace(os.sep, '/')
        try:
            lines = open(path, encoding='utf-8', errors='replace').read().splitlines()
        except Exception:
            continue

        axioms = 0
        # Per-theorem attribution: a declaration's body runs until the next
        # top-level declaration, so the tactic that closes THIS theorem is the
        # one found inside its own block.
        blocks = []   # (kind, text)
        cur_kind, cur = None, []
        for ln in lines:
            m = DECL.match(ln)
            if m and (TOP.match(ln) or m.group(1) in ('theorem', 'lemma')):
                if cur_kind:
                    blocks.append((cur_kind, '\n'.join(cur)))
                cur_kind, cur = m.group(1), [ln]
                if m.group(1) == 'axiom':
                    axioms += 1
            elif cur_kind:
                cur.append(ln)
        if cur_kind:
            blocks.append((cur_kind, '\n'.join(cur)))

        thm = clean = dec = nat = srr = 0
        for kind, text in blocks:
            if kind not in ('theorem', 'lemma'):
                continue
            thm += 1
            if re.search(r'\bsorry\b', text):
                srr += 1
            elif 'native_decide' in text:
                nat += 1
            elif re.search(r'\bdecide\b', text):
                dec += 1
            else:
                clean += 1
        rows.append((rel, thm, srr, axioms, dec, nat, clean))

rows.sort()
with open(out, 'w', encoding='utf-8') as f:
    f.write(f"// lean_census.rs -- GENERATED by scan_lean_census.sh on {stamp}. Do not hand-edit.\n")
    f.write("// The kernel has no filesystem; `redteam audit` and `provenance` read this census.\n")
    f.write("// Counts are PER THEOREM: `clean` are theorems closed WITHOUT sorry, decide or\n")
    f.write("// native_decide, so one finite check no longer demotes a whole file.\n")
    f.write("#![allow(dead_code)]\n\n")
    f.write("pub struct LeanFile {\n    pub path: &'static str,\n    pub theorems: u16,\n"
            "    pub sorries: u16,\n    pub axioms: u16,\n    pub decide: u16,\n"
            "    pub native_decide: u16,\n    pub clean: u16,\n}\n\n")
    f.write(f'pub const CENSUS_DATE: &str = "{stamp}";\n\n')
    f.write("pub static LEAN_CENSUS: &[LeanFile] = &[\n")
    for rel, thm, srr, ax, dec, nat, clean in rows:
        f.write(f'    LeanFile {{ path: "{rel}", theorems: {thm}, sorries: {srr}, axioms: {ax}, '
                f'decide: {dec}, native_decide: {nat}, clean: {clean} }},\n')
    f.write("];\n")
print(f"wrote {out}: {len(rows)} entries (census {stamp})")
PY
