#!/usr/bin/env python3
"""Five stages of the same real benchmark, `gpu_sixteen3_tensor_kernel <n>`
on the RTX 4070, n from 10^4 to 10^9, one boot per point so CUDA
context/module setup happens once and every number is the module's own
internal Instant timing, not shell wall-clock including boot.

STAGE 1 (*_before_gpu_verify.csv): the original module. Verification was a
single-threaded CPU loop reading every GPU result back and recomputing it
against imasm_core.

STAGE 2 (*_gpu_verify_host_rng.csv): verification moved onto the GPU --
every thread also computes the same three stages via an independently-
written flat kernel and folds disagreement into one atomic counter per
stage, O(N) work that never leaves the device. Input triples were still
generated by a host-side loop and copied to the device (htod).

STAGE 3 (*_gpu_verify_gpu_rng.csv): input generation moved onto the GPU
too -- each thread derives its own x, y, z from its own index and a seed
(a MurmurHash3-finalizer mix, counter-based, no host loop, no htod). x/y/z
and all three stage-output arrays were still allocated and written at full
n length.

STAGE 4 (*_gpu_verify_gpu_rng_k_inputs.csv): device allocations switched
from alloc_zeros to alloc for the six per-element buffers (every element
is unconditionally overwritten before any read, so zeroing first was
waste -- measured alone, this landed inside run-to-run noise, not a real
win by itself). The regenerated x/y/z buffers shrunk from length n to
length k=10,000, the actual number the control check ever reads back.

STAGE 5 (gpu_sixteen3_tensor_kernel_scaling.csv, current): stage1/stage2
(the two intermediate results the protocol chains THROUGH on the way to
the final one, per phase_4 step 9's own "chain into the next gate")
shrunk from length n to length k too. Only stage3 -- what phase_4 step 11
calls "the FINAL computed tensor," singular -- is still materialized at
full n length; it is this kernel's actual product, everything else is
either fully cross-checked in registers via atomics (never needs a global
array to do that) or read back only for the fixed-size CPU control.
"""
import csv
import matplotlib.pyplot as plt

def load(path):
    rows = []
    with open(path) as f:
        for row in csv.DictReader(f):
            rows.append({k: float(v) for k, v in row.items() if k != "control_k"})
    return rows

s1 = load("gpu_sixteen3_tensor_kernel_scaling_before_gpu_verify.csv")
s2 = load("gpu_sixteen3_tensor_kernel_scaling_gpu_verify_host_rng.csv")
s3 = load("gpu_sixteen3_tensor_kernel_scaling_gpu_verify_gpu_rng.csv")
s4 = load("gpu_sixteen3_tensor_kernel_scaling_gpu_verify_gpu_rng_k_inputs.csv")
s5 = load("gpu_sixteen3_tensor_kernel_scaling.csv")

stages = [
    ("1: CPU-loop verify (original)", s1, "tab:red", "o--"),
    ("2: GPU verify, host RNG", s2, "tab:orange", "o-."),
    ("3: GPU verify + GPU RNG, full-n buffers", s3, "tab:green", "o:"),
    ("4: + alloc not alloc_zeros, k-sized inputs", s4, "tab:purple", "o--"),
    ("5: + k-sized intermediates (current)", s5, "tab:blue", "o-"),
]

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(13, 5.2))

for label, rows, color, style in stages:
    n = [r["n"] for r in rows]
    total = [r["total_ms"] for r in rows]
    lw = 2.2 if rows is s5 else 1.4
    ax1.plot(n, total, style, color=color, label=label, linewidth=lw)
ax1.set_xscale("log")
ax1.set_yscale("log")
ax1.set_xlabel("register triples (n)")
ax1.set_ylabel("total elapsed (ms)")
ax1.set_title("five stages of the same benchmark")
ax1.legend(fontsize=7, loc="upper left")
ax1.grid(True, which="both", alpha=0.25)

n1 = [r["n"] for r in s1]
total1 = [r["total_ms"] for r in s1]
for label, rows, color, style in stages[1:]:
    n = [r["n"] for r in rows]
    total = [r["total_ms"] for r in rows]
    speedup = [a / b for a, b in zip(total1, total)]
    lw = 2.2 if rows is s5 else 1.4
    ax2.plot(n, speedup, style, color=color, label=label.split(":")[0] + " vs 1", linewidth=lw)
ax2.set_xscale("log")
ax2.set_yscale("log")
ax2.set_xlabel("register triples (n)")
ax2.set_ylabel("speedup vs stage 1 (original)")
ax2.set_title("cumulative speedup, total wall time")
ax2.legend(fontsize=7.5, loc="upper left")
ax2.grid(True, which="both", alpha=0.25)
ax2.axhline(1.0, color="gray", linewidth=0.8)
n5 = [r["n"] for r in s5]
total5 = [r["total_ms"] for r in s5]
speedup5 = [a / b for a, b in zip(total1, total5)]
for x, y in zip(n5, speedup5):
    ax2.annotate(f"{y:.0f}x", (x, y), textcoords="offset points", xytext=(0, 8), fontsize=8, ha="center", color="tab:blue")

fig.suptitle(
    "gpu_sixteen3_tensor_kernel: chained union -> meet_t -> truth_swap on the RTX 4070\n"
    "one boot per point, internal Instant timing, 10^4 to 10^9 register triples",
    fontsize=10,
)
fig.tight_layout(rect=[0, 0, 1, 0.93])
fig.savefig("gpu_sixteen3_tensor_kernel_scaling.png", dpi=150)
print("wrote gpu_sixteen3_tensor_kernel_scaling.png")
for x, y in zip(n5, speedup5):
    print(f"  n={int(x):>12}  {y:.1f}x cumulative")
