#!/usr/bin/env python3
"""Three stages of the same real benchmark, `gpu_sixteen3_tensor_kernel <n>`
on the RTX 4070, n from 10^4 to 10^9, one boot per point so CUDA
context/module setup happens once and every number is the module's own
internal Instant timing, not shell wall-clock including boot.

STAGE 1 (*_before_gpu_verify.csv): the original module. Verification was a
single-threaded CPU loop reading every GPU result back and recomputing it
against imasm_core.

STAGE 2 (*_gpu_verify_host_rng.csv): verification moved onto the GPU --
every thread also computes the same three stages via an independently-
written flat kernel and folds disagreement into one atomic counter per
stage, O(N) work that never leaves the device. Input triples were still
generated by a host-side loop and copied to the device (htod).

STAGE 3 (gpu_sixteen3_tensor_kernel_scaling.csv, current): input generation
moved onto the GPU too -- each thread derives its own x, y, z from its own
index and a seed (a MurmurHash3-finalizer mix, counter-based, no host loop,
no htod of the inputs at all). A fixed 10,000-entry sample, regardless of
n, is still read back and checked directly against the real CPU imasm_core
functions at every stage -- the ground-truth control a GPU-only
self-consistency check cannot be.
"""
import csv
import matplotlib.pyplot as plt

def load(path):
    rows = []
    with open(path) as f:
        for row in csv.DictReader(f):
            rows.append({k: float(v) for k, v in row.items() if k != "control_k"})
    return rows

s1 = load("gpu_sixteen3_tensor_kernel_scaling_before_gpu_verify.csv")
s2 = load("gpu_sixteen3_tensor_kernel_scaling_gpu_verify_host_rng.csv")
s3 = load("gpu_sixteen3_tensor_kernel_scaling.csv")

n1, total1 = [r["n"] for r in s1], [r["total_ms"] for r in s1]
n2, total2 = [r["n"] for r in s2], [r["total_ms"] for r in s2]
n3, total3 = [r["n"] for r in s3], [r["total_ms"] for r in s3]
gen2 = [r["gen_ms"] for r in s2]  # stage 2's host RNG cost, gone by stage 3

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(13, 5.2))

ax1.plot(n1, total1, "o--", color="tab:red", label="1: CPU-loop verify (original)")
ax1.plot(n2, total2, "o-.", color="tab:orange", label="2: GPU verify, host RNG")
ax1.plot(n2, gen2, "s:", color="tab:orange", alpha=0.6, label="2: host RNG generation alone")
ax1.plot(n3, total3, "o-", color="tab:blue", linewidth=2, label="3: GPU verify + GPU RNG (current)")
ax1.set_xscale("log")
ax1.set_yscale("log")
ax1.set_xlabel("register triples (n)")
ax1.set_ylabel("total elapsed (ms)")
ax1.set_title("three stages of the same benchmark")
ax1.legend(fontsize=8, loc="upper left")
ax1.grid(True, which="both", alpha=0.25)

speedup_2 = [a / b for a, b in zip(total1, total2)]
speedup_3 = [a / b for a, b in zip(total1, total3)]
ax2.plot(n2, speedup_2, "o-.", color="tab:orange", label="stage 2 vs stage 1")
ax2.plot(n3, speedup_3, "o-", color="tab:blue", linewidth=2, label="stage 3 vs stage 1 (cumulative)")
ax2.set_xscale("log")
ax2.set_yscale("log")
ax2.set_xlabel("register triples (n)")
ax2.set_ylabel("speedup vs stage 1 (original)")
ax2.set_title("cumulative speedup, total wall time")
ax2.legend(fontsize=8, loc="upper left")
ax2.grid(True, which="both", alpha=0.25)
ax2.axhline(1.0, color="gray", linewidth=0.8)
for x, y in zip(n3, speedup_3):
    ax2.annotate(f"{y:.0f}x", (x, y), textcoords="offset points", xytext=(0, 8), fontsize=8, ha="center", color="tab:blue")

fig.suptitle(
    "gpu_sixteen3_tensor_kernel: chained union -> meet_t -> truth_swap on the RTX 4070\n"
    "one boot per point, internal Instant timing, 10^4 to 10^9 register triples",
    fontsize=10,
)
fig.tight_layout(rect=[0, 0, 1, 0.93])
fig.savefig("gpu_sixteen3_tensor_kernel_scaling.png", dpi=150)
print("wrote gpu_sixteen3_tensor_kernel_scaling.png")
for x, y in zip(n3, speedup_3):
    print(f"  n={int(x):>12}  {y:.1f}x cumulative")
