#!/usr/bin/env python3
"""Emit src/canonical_ig.rs from the canonical Python sources.

The kernel had the twelve-axis order written out by hand in ten files, in two
different alphabets, plus its own copies of the value glyphs, the ordinals, the
weights and the CL8NK formula fragments. None of that is the kernel's to decide.
It is emitted here so the Rust carries the same table the rest of the system
reads, and drifts only when the source does.

Sources:
  imscrbgrmr/canonical_primitives.py  — order, names, values, ordinals, weights
  navigators/cl8nk_navigator.py       — CL8NK_FORMULAE (fragment, atom, proximity)

Output is no_std-safe: plain static slices and linear lookups, no allocation.
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
IG = ROOT / "imscribing_grammar"
OUT = Path(__file__).resolve().parent.parent / "src" / "canonical_ig.rs"

sys.path.insert(0, str(IG))
sys.path.insert(0, str(IG / "navigators"))
from imscrbgrmr import canonical_primitives as cp          # noqa: E402
import cl8nk_navigator as nav                              # noqa: E402


def rs(s: str) -> str:
    return '"%s"' % s.replace("\\", "\\\\").replace('"', '\\"')


def main() -> None:
    order = list(cp.PRIMITIVE_ORDER)
    if len(order) != 12:
        raise SystemExit("canonical_primitives.PRIMITIVE_ORDER is not twelve axes")

    L = []
    L.append("// AUTO-GENERATED by tools/gen_canonical_ig.py — do not hand-edit.")
    L.append("// Source: imscrbgrmr/canonical_primitives.py + navigators/cl8nk_navigator.py")
    L.append("// Regenerate after any change to the alphabet, the ordinals or the")
    L.append("// CL8NK formulae. `make ordinals` guards ordinal drift against Lean.")
    L.append("#![allow(dead_code)]")
    L.append("")
    L.append("/// The twelve axis marks, in canonical order.")
    L.append("pub static PRIMITIVE_ORDER: [&str; 12] = [%s];"
             % ", ".join(rs(p) for p in order))
    L.append("")
    L.append("/// Axis mark to the axis's name.")
    L.append("pub static PRIMITIVE_NAMES: [(&str, &str); 12] = [")
    for p in order:
        L.append("    (%s, %s)," % (rs(p), rs(cp.PRIMITIVE_NAMES[p])))
    L.append("];")
    L.append("")
    L.append("/// Each axis's values, in ordinal order.")
    L.append("pub static CANONICAL_VALUES: [(&str, &[&str]); 12] = [")
    for p in order:
        vals = list(cp.CANONICAL_VALUES[p])
        L.append("    (%s, &[%s])," % (rs(p), ", ".join(rs(v) for v in vals)))
    L.append("];")
    L.append("")
    L.append("/// Value to its ordinal rank. Not every axis is consecutive:")
    L.append("/// Kinetics puts many-body localisation at 4.5, above trapped.")
    L.append("pub static ORDINALS: [(&str, &[(&str, f32)]); 12] = [")
    for p in order:
        items = cp.ORDINALS[p]
        pairs = ", ".join("(%s, %s)" % (rs(v), float(o)) for v, o in items.items())
        L.append("    (%s, &[%s])," % (rs(p), pairs))
    L.append("];")
    L.append("")
    L.append("/// Per-axis distance weights.")
    L.append("pub static WEIGHTS: [(&str, f32); 12] = [")
    for p in order:
        L.append("    (%s, %s)," % (rs(p), float(cp.WEIGHTS[p])))
    L.append("];")
    L.append("")
    L.append("/// CL8NK formula fragments: axis -> value -> (fragment, atom, proximity).")
    L.append("/// An empty atom means the value promotes no atom.")
    L.append("pub static CL8NK_FORMULAE: [(&str, &[(&str, &str, &str, &str)]); 12] = [")
    for p in order:
        rows = nav.CL8NK_FORMULAE.get(p, {})
        cells = []
        for glyph, tup in rows.items():
            frag = tup[0] if len(tup) > 0 else ""
            atom = tup[1] if len(tup) > 1 and tup[1] else ""
            prox = tup[2] if len(tup) > 2 and tup[2] else ""
            cells.append("(%s, %s, %s, %s)" % (rs(glyph), rs(frag), rs(atom), rs(prox)))
        L.append("    (%s, &[%s])," % (rs(p), ", ".join(cells)))
    L.append("];")
    L.append("")
    L.append("""
/// The axis a value belongs to, or None if the value is off every axis.
pub fn axis_of(value: &str) -> Option<&'static str> {
    for (axis, vals) in CANONICAL_VALUES.iter() {
        for v in vals.iter() {
            if *v == value { return Some(axis); }
        }
    }
    None
}

/// A value's ordinal rank on its axis.
pub fn ordinal_of(axis: &str, value: &str) -> Option<f32> {
    for (a, rows) in ORDINALS.iter() {
        if *a != axis { continue; }
        for (v, o) in rows.iter() {
            if *v == value { return Some(*o); }
        }
    }
    None
}

/// The name of an axis.
pub fn name_of(axis: &str) -> Option<&'static str> {
    for (a, n) in PRIMITIVE_NAMES.iter() {
        if *a == axis { return Some(n); }
    }
    None
}

/// The distance weight of an axis.
pub fn weight_of(axis: &str) -> Option<f32> {
    for (a, w) in WEIGHTS.iter() {
        if *a == axis { return Some(*w); }
    }
    None
}

/// The CL8NK fragment, promoted atom and proximity for a value.
pub fn formula_of(axis: &str, value: &str) -> Option<(&'static str, &'static str, &'static str)> {
    for (a, rows) in CL8NK_FORMULAE.iter() {
        if *a != axis { continue; }
        for (v, frag, atom, prox) in rows.iter() {
            if *v == value { return Some((frag, atom, prox)); }
        }
    }
    None
}

/// Index of an axis in canonical order.
pub fn axis_index(axis: &str) -> Option<usize> {
    let mut i = 0;
    while i < PRIMITIVE_ORDER.len() {
        if PRIMITIVE_ORDER[i] == axis { return Some(i); }
        i += 1;
    }
    None
}
""".rstrip())
    L.append("")
    OUT.write_text("\n".join(L), encoding="utf-8")

    n_vals = sum(len(cp.CANONICAL_VALUES[p]) for p in order)
    n_form = sum(len(nav.CL8NK_FORMULAE.get(p, {})) for p in order)
    print("wrote %s" % OUT.relative_to(OUT.parent.parent))
    print("  12 axes, %d values, %d ordinals, %d CL8NK fragments"
          % (n_vals, sum(len(cp.ORDINALS[p]) for p in order), n_form))


main()
