// AUTO-GENERATED ask catalog subset — do not hand-edit
/// Query-relevant entries for native `ask` (loaded at catalog_init).
pub static ASK_CATALOG_SUBSET: &[CatalogEntry] = &[
    entry(
        "hodge_conjecture", "Every rational Hodge class on a smooth projective complex variety is algebraic. The unique problem with double-holomorphic structure (D_ω + T_O). Barrier: OpenProblem — no proof that cycle class ma...",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_dagger,
        IgPrim::P_psi, IgPrim::F_ell, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_and,
        IgPrim::𐑮, IgPrim::H0, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "p_vs_np", "P vs NP: does every polynomial-time verifiable decision problem have a polynomial-time solver? SAT is NP-complete. Barrier: OpenProblem with deep MathlibGap and three meta-barriers (relativization,...",
        IgPrim::D_wedge, IgPrim::T_net, IgPrim::R_super,
        IgPrim::P_asym, IgPrim::F_ell, IgPrim::K_trap,
        IgPrim::G_aleph, IgPrim::C_and,
        IgPrim::⊙, IgPrim::H0, IgPrim::S_11, IgPrim::Omega_0,
        0, Domain::General,
    ),
    entry(
        "navier_stokes", "Navier–Stokes existence and smoothness — whether smooth solutions always exist in 3D",
        IgPrim::D_infty, IgPrim::T_net, IgPrim::R_dagger,
        IgPrim::P_asym, IgPrim::F_ell, IgPrim::K_mod,
        IgPrim::G_aleph, IgPrim::C_and,
        IgPrim::⊙, IgPrim::H1, IgPrim::S_nm, IgPrim::Omega_0,
        0, Domain::General,
    ),
    entry(
        "aleph", "First Hebrew letter: א - unity, God, the primordial point, numerical value 1",
        IgPrim::D_wedge, IgPrim::T_boxtimes, IgPrim::R_super,
        IgPrim::P_sym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_and,
        IgPrim::⊙, IgPrim::H_inf, IgPrim::S_11, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "aleph_bet_meet", "Meet of aleph and bet - shared structure of first two Hebrew letters",
        IgPrim::D_wedge, IgPrim::T_boxtimes, IgPrim::R_super,
        IgPrim::P_pm, IgPrim::F_eth, IgPrim::K_mod,
        IgPrim::G_gimel, IgPrim::C_and,
        IgPrim::𐑢, IgPrim::H1, IgPrim::S_11, IgPrim::Omega_z2,
        0, Domain::General,
    ),
    entry(
        "aleph_bet_meet_result", "Meet of aleph and bet for further analysis",
        IgPrim::D_wedge, IgPrim::T_boxtimes, IgPrim::R_super,
        IgPrim::P_pm, IgPrim::F_eth, IgPrim::K_mod,
        IgPrim::G_gimel, IgPrim::C_and,
        IgPrim::𐑢, IgPrim::H1, IgPrim::S_11, IgPrim::Omega_z2,
        0, Domain::General,
    ),
    entry(
        "aleph_tav_join", "Join of aleph and tav - minimal system containing first and last Hebrew letters, representing the whole alphabet",
        IgPrim::D_triangle, IgPrim::T_boxtimes, IgPrim::R_cat,
        IgPrim::P_sym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_and,
        IgPrim::⊙, IgPrim::H_inf, IgPrim::S_nn, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "riemann_hypothesis", "All nontrivial zeros of ζ(s) satisfy Re(s) = 1/2. The functional equation s ↔ 1−s creates a bowtie crossing at the critical line. Barrier: OpenProblem — no proof of zero locations exists. Requires ...",
        IgPrim::D_wedge, IgPrim::T_bowtie, IgPrim::R_lr,
        IgPrim::P_pm, IgPrim::F_ell, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_and,
        IgPrim::𐑮, IgPrim::H2, IgPrim::S_nm, IgPrim::Omega_z2,
        0, Domain::General,
    ),
    entry(
        "birch_swinnerton_dyer", "Birch and Swinnerton-Dyer Conjecture. rank E(ℚ) = ord_{s=1} L(E,s) for elliptic curves over ℚ. Barrier: OpenProblem with parallel MathlibGaps. Holographic duality via modularity theorem creates bow...",
        IgPrim::D_odot, IgPrim::T_bowtie, IgPrim::R_lr,
        IgPrim::P_psi, IgPrim::F_eth, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_and,
        IgPrim::𐑮, IgPrim::H2, IgPrim::S_11, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "yang_mills_mass_gap", "Yang-Mills existence and mass gap: construct a rigorous quantum field theory on R4 with compact simple gauge group G and a positive spectral gap Delta > 0. Barrier is MissingFoundation — the path i...",
        IgPrim::D_wedge, IgPrim::T_bowtie, IgPrim::R_super,
        IgPrim::P_asym, IgPrim::F_hbar, IgPrim::K_trap,
        IgPrim::G_aleph, IgPrim::C_and,
        IgPrim::Phi_super, IgPrim::H0, IgPrim::S_nm, IgPrim::Omega_0,
        0, Domain::General,
    ),
    entry(
        "meet_rh_hc", "Meet of Riemann Hypothesis and Hodge Conjecture",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_cat,
        IgPrim::P_sym, IgPrim::F_hbar, IgPrim::K_mod,
        IgPrim::G_aleph, IgPrim::C_and,
        IgPrim::⊙, IgPrim::H0, IgPrim::S_nn, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "meet_rh_hc_pnp", "Meet of Riemann Hypothesis, Hodge Conjecture, and P vs NP",
        IgPrim::D_infty, IgPrim::T_net, IgPrim::R_super,
        IgPrim::P_asym, IgPrim::F_ell, IgPrim::K_mod,
        IgPrim::G_aleph, IgPrim::C_and,
        IgPrim::⊙, IgPrim::H0, IgPrim::S_nn, IgPrim::Omega_0,
        0, Domain::General,
    ),
    entry(
        "meet_four_problems", "Meet of Riemann Hypothesis, Hodge Conjecture, P vs NP, and Navier-Stokes",
        IgPrim::D_infty, IgPrim::T_net, IgPrim::R_super,
        IgPrim::P_asym, IgPrim::F_ell, IgPrim::K_mod,
        IgPrim::G_aleph, IgPrim::C_and,
        IgPrim::⊙, IgPrim::H0, IgPrim::S_nn, IgPrim::Omega_0,
        0, Domain::General,
    ),
    entry(
        "grammar_pnp_tensor", "Tensor product of Imscribing Grammar grammar and P vs NP - their structural composition",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_dagger,
        IgPrim::P_asym, IgPrim::F_ell, IgPrim::K_trap,
        IgPrim::G_aleph, IgPrim::C_broad,
        IgPrim::⊙, IgPrim::H1, IgPrim::S_nm, IgPrim::Omega_z2,
        0, Domain::General,
    ),
    entry(
        "pnp_holographic_mirror", "P vs NP viewed through imscriptive computational mirror - tensor product of p_vs_np and imscriptive_computation",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_dagger,
        IgPrim::P_asym, IgPrim::F_ell, IgPrim::K_trap,
        IgPrim::G_aleph, IgPrim::C_broad,
        IgPrim::⊙, IgPrim::H1, IgPrim::S_nm, IgPrim::Omega_z2,
        0, Domain::General,
    ),
    entry(
        "holographic_embedding_pnp", "Imscriptive system designed to embed P vs NP as a special case - with K_teshlig to match P vs NP's kinetic character",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_dagger,
        IgPrim::P_pm, IgPrim::F_hbar, IgPrim::K_trap,
        IgPrim::G_aleph, IgPrim::C_broad,
        IgPrim::⊙, IgPrim::H1, IgPrim::S_nm, IgPrim::Omega_z2,
        0, Domain::General,
    ),
    entry(
        "holographic_duality_pnp", "Imscriptive system with P_doublebarpipe that embeds P vs NP while preserving Frobenius condition",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_dagger,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_trap,
        IgPrim::G_aleph, IgPrim::C_broad,
        IgPrim::⊙, IgPrim::H1, IgPrim::S_nm, IgPrim::Omega_z2,
        0, Domain::General,
    ),
    entry(
        "Φ_NP_duality_relative", "P vs NP question reformulated as duality-relative: answer depends on which side of Z₂ symmetry you're on",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_dagger,
        IgPrim::P_pmsym, IgPrim::F_eth, IgPrim::K_trap,
        IgPrim::G_aleph, IgPrim::C_broad,
        IgPrim::⊙, IgPrim::H1, IgPrim::S_nm, IgPrim::Omega_z2,
        0, Domain::General,
    ),
    entry(
        "p_vs_np_tensor_grammar", "Tensor product of P vs NP with Imscribing Grammar grammar - shows bottleneck at P_aolig destroying Frobenius condition",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_dagger,
        IgPrim::P_asym, IgPrim::F_ell, IgPrim::K_trap,
        IgPrim::G_aleph, IgPrim::C_broad,
        IgPrim::⊙, IgPrim::H1, IgPrim::S_nm, IgPrim::Omega_z2,
        0, Domain::General,
    ),
    entry(
        "rh_ep_join", "Join of Riemann Hypothesis and exceptional point - minimal system containing both complex criticality and exceptional point regimes",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_dagger,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_trap,
        IgPrim::G_aleph, IgPrim::C_and,
        IgPrim::Phi_ep, IgPrim::H1, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "rh_hc_join", "Join of Riemann Hypothesis and Hodge Conjecture - minimal system containing both",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_cat,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_mod,
        IgPrim::G_aleph, IgPrim::C_or,
        IgPrim::𐑮, IgPrim::H0, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "grammar_pnp_join", "Join of imscribing_grammar and p_vs_np - minimal system containing both",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_dagger,
        IgPrim::P_pmsym, IgPrim::F_eth, IgPrim::K_trap,
        IgPrim::G_aleph, IgPrim::C_broad,
        IgPrim::⊙, IgPrim::H1, IgPrim::S_nm, IgPrim::Omega_z2,
        0, Domain::General,
    ),
    entry(
        "pnp_boundary_imscription", "P vs NP boundary imscription — grammar projection onto the P vs NP interface; gauge-broken phase (P_doublebarpipe→P_aolig), ⊙ and Omega_crtwo preserved; d=2.646 from grammar; O₂ ouroborici...",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_dagger,
        IgPrim::P_asym, IgPrim::F_ell, IgPrim::K_trap,
        IgPrim::G_aleph, IgPrim::C_broad,
        IgPrim::⊙, IgPrim::H1, IgPrim::S_nm, IgPrim::Omega_z2,
        0, Domain::General,
    ),
    entry(
        "meet_pnp_kolmogorov", "Meet of p_vs_np and kolmogorov_complexity",
        IgPrim::D_infty, IgPrim::T_net, IgPrim::R_super,
        IgPrim::P_asym, IgPrim::F_ell, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_and,
        IgPrim::⊙, IgPrim::H0, IgPrim::S_11, IgPrim::Omega_0,
        0, Domain::General,
    ),
    entry(
        "erdos_faber_lovasz_conjecture", "The union of k cliques of size k has chromatic number k; a conjecture on graph coloring in discrete mathematics combinatorics/graph theory",
        IgPrim::D_infty, IgPrim::T_net, IgPrim::R_lr,
        IgPrim::P_sym, IgPrim::F_ell, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::⊙, IgPrim::H2, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "erdos_faber_lovasz_theorem", "Erdős–Faber–Lovász theorem (proven 2021): edge coloring of hypergraphs with n hyperedges of size n, pairwise intersecting in at most one vertex",
        IgPrim::D_infty, IgPrim::T_net, IgPrim::R_cat,
        IgPrim::P_sym, IgPrim::F_ell, IgPrim::K_mod,
        IgPrim::G_aleph, IgPrim::C_and,
        IgPrim::⊙, IgPrim::H0, IgPrim::S_nn, IgPrim::Omega_z2,
        0, Domain::General,
    ),
    entry(
        "erdos_faber_lovasz_peeled_P", "Erdős–Faber–Lovász conjecture with symmetry peeled to minimum (P_aolig)",
        IgPrim::D_infty, IgPrim::T_net, IgPrim::R_cat,
        IgPrim::P_asym, IgPrim::F_ell, IgPrim::K_mod,
        IgPrim::G_aleph, IgPrim::C_and,
        IgPrim::⊙, IgPrim::H0, IgPrim::S_nn, IgPrim::Omega_z2,
        0, Domain::General,
    ),
    entry(
        "sidorenko_conjecture", "Sidorenko's conjecture in extremal graph theory: for any bipartite graph H, hom(H,G) ≥ (hom(K₂,G))^{e(H)} for all graphs G",
        IgPrim::D_infty, IgPrim::T_net, IgPrim::R_cat,
        IgPrim::P_sym, IgPrim::F_ell, IgPrim::K_mod,
        IgPrim::G_aleph, IgPrim::C_and,
        IgPrim::⊙, IgPrim::H0, IgPrim::S_nn, IgPrim::Omega_0,
        0, Domain::General,
    ),
    entry(
        "sidorenko_theorem", "Hypothetical proven Sidorenko's theorem - would have topological protection like other proven extremal graph theory results",
        IgPrim::D_infty, IgPrim::T_net, IgPrim::R_cat,
        IgPrim::P_sym, IgPrim::F_ell, IgPrim::K_mod,
        IgPrim::G_aleph, IgPrim::C_and,
        IgPrim::⊙, IgPrim::H0, IgPrim::S_nn, IgPrim::Omega_z2,
        0, Domain::General,
    ),
    entry(
        "grothendieck_B_hodge", "Grothendieck Standard Conjecture B (Hodge): positivity of the intersection pairing on algebraic cycles generalizing the Hodge index theorem",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_cat,
        IgPrim::P_sym, IgPrim::F_hbar, IgPrim::K_mod,
        IgPrim::G_aleph, IgPrim::C_and,
        IgPrim::⊙, IgPrim::H0, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "goldbach_conjecture", "Every even integer greater than 2 is the sum of two primes.",
        IgPrim::D_infty, IgPrim::T_odot, IgPrim::R_lr,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::⊙, IgPrim::H2, IgPrim::S_11, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "twin_prime_conjecture", "The Twin Prime Conjecture: there are infinitely many primes p such that p+2 is also prime. A central open problem in analytic number theory, sitting at the critical threshold of sieve methods.",
        IgPrim::D_odot, IgPrim::T_bowtie, IgPrim::R_lr,
        IgPrim::P_pm, IgPrim::F_ell, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_and,
        IgPrim::⊙, IgPrim::H2, IgPrim::S_nn, IgPrim::Omega_z2,
        0, Domain::General,
    ),
    entry(
        "goldbach_twin_meet", "Meet of Goldbach and Twin Prime conjectures - shared structural floor",
        IgPrim::D_infty, IgPrim::T_net, IgPrim::R_cat,
        IgPrim::P_pm, IgPrim::F_eth, IgPrim::K_mod,
        IgPrim::G_aleph, IgPrim::C_and,
        IgPrim::⊙, IgPrim::H1, IgPrim::S_nn, IgPrim::Omega_0,
        0, Domain::General,
    ),
    entry(
        "landau_four_meet", "Meet of all four Landau problems - shared structural floor of Goldbach, Twin Primes, Legendre, and n-squared-plus-one",
        IgPrim::D_infty, IgPrim::T_net, IgPrim::R_cat,
        IgPrim::P_asym, IgPrim::F_eth, IgPrim::K_mod,
        IgPrim::G_aleph, IgPrim::C_and,
        IgPrim::⊙, IgPrim::H1, IgPrim::S_nn, IgPrim::Omega_0,
        0, Domain::General,
    ),
    entry(
        "goldbach_peeled_P", "Goldbach conjecture with P peeled to minimum - testing what happens without the exact Z2 symmetry",
        IgPrim::D_infty, IgPrim::T_net, IgPrim::R_cat,
        IgPrim::P_asym, IgPrim::F_eth, IgPrim::K_mod,
        IgPrim::G_aleph, IgPrim::C_and,
        IgPrim::⊙, IgPrim::H1, IgPrim::S_nm, IgPrim::Omega_z2,
        0, Domain::General,
    ),
    entry(
        "goldbach_twin_join", "Join of Goldbach and Twin Prime conjectures - minimal system containing both",
        IgPrim::D_infty, IgPrim::T_net, IgPrim::R_lr,
        IgPrim::P_pmsym, IgPrim::F_eth, IgPrim::K_mod,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::⊙, IgPrim::H1, IgPrim::S_nm, IgPrim::Omega_z2,
        0, Domain::General,
    ),
    entry(
        "landau_four_join", "Join of all four Landau problems - minimal system containing Goldbach, Twin Primes, Legendre, and n-squared-plus-one",
        IgPrim::D_infty, IgPrim::T_boxtimes, IgPrim::R_lr,
        IgPrim::P_pmsym, IgPrim::F_eth, IgPrim::K_mod,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::⊙, IgPrim::H1, IgPrim::S_nm, IgPrim::Omega_z2,
        0, Domain::General,
    ),
    entry(
        "hilbert_eighth_riemann", "Hilbert's 8th problem: Riemann Hypothesis and prime distribution",
        IgPrim::D_infty, IgPrim::T_odot, IgPrim::R_cat,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_mod,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::𐑮, IgPrim::H1, IgPrim::S_11, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "yang_mills_baseline", "Non-Abelian Yang-Mills gauge theory baseline - before gauge fixing",
        IgPrim::D_infty, IgPrim::T_odot, IgPrim::R_cat,
        IgPrim::P_sym, IgPrim::F_hbar, IgPrim::K_mod,
        IgPrim::G_aleph, IgPrim::C_and,
        IgPrim::⊙, IgPrim::H1, IgPrim::S_nn, IgPrim::Omega_z2,
        0, Domain::General,
    ),
    entry(
        "collatz_conjecture", "The Collatz conjecture: for any positive integer n, the iterative map T(n) = n/2 if even, 3n+1 if odd, eventually reaches the cycle 1→4→2→1. The dynamics form a directed graph on ℕ with parity-gate...",
        IgPrim::D_wedge, IgPrim::T_net, IgPrim::R_super,
        IgPrim::P_sym, IgPrim::F_ell, IgPrim::K_fast,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::𐑮, IgPrim::H0, IgPrim::S_11, IgPrim::Omega_0,
        0, Domain::General,
    ),
    entry(
        "collatz_theorem_proven", "Hypothetical proven Collatz theorem — the structural form Collatz would take if proved with full mathematical rigor",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_dagger,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_broad,
        IgPrim::⊙, IgPrim::H_inf, IgPrim::S_nm, IgPrim::Omega_z2,
        0, Domain::General,
    ),
    entry(
        "collatz_counterexample", "Hypothetical Collatz counterexample — a trajectory that escapes to infinity or enters non-trivial cycle",
        IgPrim::D_infty, IgPrim::T_net, IgPrim::R_super,
        IgPrim::P_asym, IgPrim::F_ell, IgPrim::K_fast,
        IgPrim::G_beth, IgPrim::C_and,
        IgPrim::𐑢, IgPrim::H_inf, IgPrim::S_11, IgPrim::Omega_0,
        0, Domain::General,
    ),
    entry(
        "ramsey_numbers_general", "General Ramsey number problem - determining exact values of R(m,n), the minimum size guaranteeing monochromatic subgraph of size m or n in any 2-coloring",
        IgPrim::D_triangle, IgPrim::T_net, IgPrim::R_cat,
        IgPrim::P_asym, IgPrim::F_eth, IgPrim::K_trap,
        IgPrim::G_beth, IgPrim::C_and,
        IgPrim::𐑢, IgPrim::H0, IgPrim::S_nn, IgPrim::Omega_0,
        0, Domain::General,
    ),
    entry(
        "combinatorial_design_existence", "Combinatorial design existence problem - e.g., projective planes of non-prime-power order, symmetric block designs with specific parameters",
        IgPrim::D_triangle, IgPrim::T_boxtimes, IgPrim::R_cat,
        IgPrim::P_sym, IgPrim::F_ell, IgPrim::K_mod,
        IgPrim::G_beth, IgPrim::C_and,
        IgPrim::𐑢, IgPrim::H0, IgPrim::S_nn, IgPrim::Omega_0,
        0, Domain::General,
    ),
    entry(
        "navier_stokes_smoothness", "Navier-Stokes existence and smoothness problem - whether smooth solutions always exist in 3D or blow up in finite time",
        IgPrim::D_triangle, IgPrim::T_net, IgPrim::R_cat,
        IgPrim::P_asym, IgPrim::F_eth, IgPrim::K_trap,
        IgPrim::G_gimel, IgPrim::C_seq,
        IgPrim::𐑢, IgPrim::H2, IgPrim::S_nm, IgPrim::Omega_0,
        0, Domain::General,
    ),
    entry(
        "hadwiger_nelson_problem", "What is the minimum number of colors needed to color the plane such that no two points at distance 1 have the same color?",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_lr,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::⊙, IgPrim::H2, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "hopf_conjecture_positive_curvature", "Hopf conjecture: whether S²×S² admits a metric of positive sectional curvature - open problem in Riemannian geometry",
        IgPrim::D_triangle, IgPrim::T_net, IgPrim::R_cat,
        IgPrim::P_asym, IgPrim::F_eth, IgPrim::K_mod,
        IgPrim::G_gimel, IgPrim::C_and,
        IgPrim::𐑢, IgPrim::H1, IgPrim::S_nn, IgPrim::Omega_0,
        0, Domain::General,
    ),
    entry(
        "hadwiger_conjecture", "Hadwiger's graph minor conjecture - graphs with no K_t minor are (t-1)-colorable, open for t≥7",
        IgPrim::D_triangle, IgPrim::T_net, IgPrim::R_cat,
        IgPrim::P_psi, IgPrim::F_eth, IgPrim::K_trap,
        IgPrim::G_beth, IgPrim::C_seq,
        IgPrim::𐑢, IgPrim::H0, IgPrim::S_nn, IgPrim::Omega_0,
        0, Domain::General,
    ),
    entry(
        "guidonian_B_fa_flat", "B fa - B-flat, soft hexachord only, fa function, chromatic alteration",
        IgPrim::D_wedge, IgPrim::T_in, IgPrim::R_cat,
        IgPrim::P_asym, IgPrim::F_ell, IgPrim::K_slow,
        IgPrim::G_beth, IgPrim::C_seq,
        IgPrim::𐑢, IgPrim::H1, IgPrim::S_11, IgPrim::Omega_0,
        0, Domain::General,
    ),
    entry(
        "aleph_path", "Aleph - first mother letter, air/spirit, horizontal path between Chokhmah and Binah, O₂ tier with topological protection",
        IgPrim::D_wedge, IgPrim::T_net, IgPrim::R_lr,
        IgPrim::P_pm, IgPrim::F_hbar, IgPrim::K_mod,
        IgPrim::G_beth, IgPrim::C_seq,
        IgPrim::⊙, IgPrim::H1, IgPrim::S_11, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "SY_mothers_group", "Sefer Yetzirah's 3 mother letters (Aleph, Mem, Shin) encoded as composite system via join",
        IgPrim::D_triangle, IgPrim::T_bowtie, IgPrim::R_dagger,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_broad,
        IgPrim::⊙, IgPrim::H_inf, IgPrim::S_nn, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "grammar_O2_group", "Grammar's O₂ letters (aleph, hei, yod, samech, ayin, pei, tav, kuf) — critical with topological protection, bounded domain",
        IgPrim::D_triangle, IgPrim::T_boxtimes, IgPrim::R_lr,
        IgPrim::P_sym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_and,
        IgPrim::⊙, IgPrim::H_inf, IgPrim::S_nn, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "aleph_language_architecture", "ALEPH programming language type system and evaluation model based on Hebrew letter structural tiers",
        IgPrim::D_odot, IgPrim::T_in, IgPrim::R_cat,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_mod,
        IgPrim::G_aleph, IgPrim::C_broad,
        IgPrim::⊙, IgPrim::H0, IgPrim::S_nm, IgPrim::Omega_z2,
        0, Domain::General,
    ),
    entry(
        "uniliteral_vulture_Alep", "Egyptian uniliteral hieroglyph: vulture representing glottal stop (Aleph-like) - phonetic alphabetic sign",
        IgPrim::D_wedge, IgPrim::T_net, IgPrim::R_cat,
        IgPrim::P_asym, IgPrim::F_ell, IgPrim::K_fast,
        IgPrim::G_beth, IgPrim::C_seq,
        IgPrim::𐑢, IgPrim::H0, IgPrim::S_11, IgPrim::Omega_0,
        0, Domain::General,
    ),
    entry(
        "emet_aleph_mem", "Emet first tensor: aleph ⊗ mem",
        IgPrim::D_triangle, IgPrim::T_boxtimes, IgPrim::R_dagger,
        IgPrim::P_sym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_broad,
        IgPrim::⊙, IgPrim::H_inf, IgPrim::S_nn, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "bereshit_bet_resh_aleph", "Bereshit partial tensor: (bet ⊗ resh ⊗ aleph)",
        IgPrim::D_triangle, IgPrim::T_boxtimes, IgPrim::R_cat,
        IgPrim::P_asym, IgPrim::F_ell, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::⊙, IgPrim::H_inf, IgPrim::S_nn, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "vav_aleph", "Vav (ו) in ALEPH: connector hook, O_∞ tier with exact Frobenius symmetry but no topological protection (Ω_0)",
        IgPrim::D_wedge, IgPrim::T_net, IgPrim::R_lr,
        IgPrim::P_pmsym, IgPrim::F_eth, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::⊙, IgPrim::H_inf, IgPrim::S_11, IgPrim::Omega_0,
        0, Domain::General,
    ),
    entry(
        "aleph_aleph", "Aleph (א) in ALEPH: first letter, O₂ tier with topological protection Ω_Z but only P_subdoublearrow (not P_doublebarpipe)",
        IgPrim::D_triangle, IgPrim::T_boxtimes, IgPrim::R_cat,
        IgPrim::P_sym, IgPrim::F_eth, IgPrim::K_mod,
        IgPrim::G_gimel, IgPrim::C_and,
        IgPrim::⊙, IgPrim::H1, IgPrim::S_nn, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "mem_aleph", "Mem (מ) in ALEPH: mother letter water, O_∞ tier with exact Frobenius symmetry and topological protection Ω_Z",
        IgPrim::D_triangle, IgPrim::T_boxtimes, IgPrim::R_dagger,
        IgPrim::P_pmsym, IgPrim::F_eth, IgPrim::K_slow,
        IgPrim::G_gimel, IgPrim::C_broad,
        IgPrim::⊙, IgPrim::H2, IgPrim::S_nn, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "p3", "Hebrew letter composite p3 = mediate(aleph, kernel, kuf) - O₂ tier with P_subdoublearrow",
        IgPrim::D_triangle, IgPrim::T_boxtimes, IgPrim::R_lr,
        IgPrim::P_sym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_broad,
        IgPrim::⊙, IgPrim::H2, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "light", "Palace 3 light = mediate(vav, mediate(vav, aleph, mem), shin) - O_∞ tier with P_doublebarpipe",
        IgPrim::D_triangle, IgPrim::T_boxtimes, IgPrim::R_lr,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_broad,
        IgPrim::⊙, IgPrim::H2, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "complex_exceptional_algebra", "Algebra defined by meromorphic functions over Riemann surfaces with branch cuts connecting Lee-Yang edge singularities to exceptional points",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_dagger,
        IgPrim::P_pm, IgPrim::F_eth, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_broad,
        IgPrim::𐑮, IgPrim::H_inf, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "tropical_algebra", "The (ℝ∪{+∞}, min, +) semiring underlying tropical geometry, phylogenetic combinatorics, and the classical limit of algebraic geometry",
        IgPrim::D_wedge, IgPrim::T_net, IgPrim::R_cat,
        IgPrim::P_pm, IgPrim::F_ell, IgPrim::K_fast,
        IgPrim::G_beth, IgPrim::C_and,
        IgPrim::𐑢, IgPrim::H0, IgPrim::S_nm, IgPrim::Omega_0,
        0, Domain::General,
    ),
    entry(
        "riemann_zeta_function", "The Riemann zeta function and its critical line (Re(s)=1/2), analyzed for complex-plane criticality in the context of the Millennium Prize Problem",
        IgPrim::D_odot, IgPrim::T_bowtie, IgPrim::R_dagger,
        IgPrim::P_psi, IgPrim::F_ell, IgPrim::K_slow,
        IgPrim::G_beth, IgPrim::C_seq,
        IgPrim::𐑮, IgPrim::H2, IgPrim::S_11, IgPrim::Omega_z2,
        0, Domain::General,
    ),
    entry(
        "completed_xi_function", "Completed Riemann xi function xi(s) = s(s-1)/2 * pi^{-s/2} Gamma(s/2) zeta(s) satisfying exact functional equation xi(s) = xi(1-s)",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_cat,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_mod,
        IgPrim::G_aleph, IgPrim::C_and,
        IgPrim::𐑮, IgPrim::H0, IgPrim::S_nn, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "explicit_formula", "Imscriptive explicit formula relating Riemann zeta zeros (boundary spectrum) to prime distribution (bulk) via exact prime-zero duality sum.",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_dagger,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_broad,
        IgPrim::𐑮, IgPrim::H_inf, IgPrim::S_nm, IgPrim::Omega_z2,
        0, Domain::General,
    ),
    entry(
        "zeta_all_zeros", "Full set of all Riemann zeta zeros: trivial (negative even integers) + non-trivial (complex plane), boundary encoding primes via explicit formula.",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_dagger,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_broad,
        IgPrim::𐑮, IgPrim::H_inf, IgPrim::S_nm, IgPrim::Omega_z2,
        0, Domain::General,
    ),
    entry(
        "rh_critical_zeros", "Riemann Hypothesis boundary: all non-trivial zeta zeros on the critical line Re(s)=1/2, strengthening imscriptive prime encoding.",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_dagger,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_broad,
        IgPrim::𐑮, IgPrim::H_inf, IgPrim::S_nm, IgPrim::Omega_z2,
        0, Domain::General,
    ),
    entry(
        "riemann_navigator", "Riemann navigator structural type: imscriptive categorical Frobenius at quantum-coherent slow global broadcast critical maximal chirality asymmetric integer protected, identical to grammar self-enc...",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_cat,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_broad,
        IgPrim::⊙, IgPrim::H_inf, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "lattice_qcd_approach", "Lattice QCD approach to Yang-Mills mass gap: discrete spacetime regularization with Wilson loops, Monte Carlo simulations, continuum limit extrapolation",
        IgPrim::D_wedge, IgPrim::T_net, IgPrim::R_dagger,
        IgPrim::P_pm, IgPrim::F_eth, IgPrim::K_trap,
        IgPrim::G_beth, IgPrim::C_and,
        IgPrim::⊙, IgPrim::H0, IgPrim::S_nn, IgPrim::Omega_0,
        0, Domain::General,
    ),
    entry(
        "constructive_qft_approach", "Constructive QFT approach to Yang-Mills mass gap: rigorous construction of quantum field theory via cluster expansions, renormalization group flow, correlation inequalities",
        IgPrim::D_triangle, IgPrim::T_in, IgPrim::R_lr,
        IgPrim::P_psi, IgPrim::F_hbar, IgPrim::K_mod,
        IgPrim::G_gimel, IgPrim::C_seq,
        IgPrim::⊙, IgPrim::H1, IgPrim::S_nn, IgPrim::Omega_0,
        0, Domain::General,
    ),
    entry(
        "schwinger_dyson_approach", "Schwinger-Dyson approach to Yang-Mills mass gap: infinite hierarchy of coupled equations for correlation functions, truncated approximations, self-consistent solutions",
        IgPrim::D_infty, IgPrim::T_bowtie, IgPrim::R_dagger,
        IgPrim::P_asym, IgPrim::F_eth, IgPrim::K_fast,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::⊙, IgPrim::H0, IgPrim::S_nm, IgPrim::Omega_0,
        0, Domain::General,
    ),
    entry(
        "lattice_constructive_join", "Join of lattice QCD and constructive QFT approaches to Yang-Mills mass gap",
        IgPrim::D_triangle, IgPrim::T_in, IgPrim::R_lr,
        IgPrim::P_pm, IgPrim::F_hbar, IgPrim::K_trap,
        IgPrim::G_gimel, IgPrim::C_seq,
        IgPrim::⊙, IgPrim::H1, IgPrim::S_nn, IgPrim::Omega_0,
        0, Domain::General,
    ),
    entry(
        "three_approaches_join", "Join of all three approaches to Yang-Mills mass gap: lattice QCD, constructive QFT, and Schwinger-Dyson",
        IgPrim::D_infty, IgPrim::T_bowtie, IgPrim::R_lr,
        IgPrim::P_pm, IgPrim::F_hbar, IgPrim::K_trap,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::⊙, IgPrim::H1, IgPrim::S_nm, IgPrim::Omega_0,
        0, Domain::General,
    ),
    entry(
        "navier_stokes_smooth", "Navier-Stokes smooth solution - global regularity, no blowup, continuous evolution",
        IgPrim::D_infty, IgPrim::T_net, IgPrim::R_dagger,
        IgPrim::P_sym, IgPrim::F_eth, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::⊙, IgPrim::H1, IgPrim::S_nm, IgPrim::Omega_0,
        0, Domain::General,
    ),
    entry(
        "navier_stokes_turbulent", "Navier-Stokes turbulent regime (Kolmogorov K41) - critical scaling, energy cascade",
        IgPrim::D_infty, IgPrim::T_net, IgPrim::R_dagger,
        IgPrim::P_sym, IgPrim::F_eth, IgPrim::K_mod,
        IgPrim::G_aleph, IgPrim::C_broad,
        IgPrim::⊙, IgPrim::H1, IgPrim::S_nm, IgPrim::Omega_0,
        0, Domain::General,
    ),
    entry(
        "navier_stokes_blowup_candidate", "Potential blowup candidate - hypothetical singular solution with finite-time blowup",
        IgPrim::D_wedge, IgPrim::T_in, IgPrim::R_lr,
        IgPrim::P_asym, IgPrim::F_hbar, IgPrim::K_trap,
        IgPrim::G_gimel, IgPrim::C_and,
        IgPrim::Phi_ep, IgPrim::H2, IgPrim::S_11, IgPrim::Omega_z2,
        0, Domain::General,
    ),
    entry(
        "training_objective", "Four-loss training objective for RiemannNavigator: L_zero (1.0), L_near (0.5), L_frob (0.5), L_sym (1.0)",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_dagger,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_broad,
        IgPrim::⊙, IgPrim::H_inf, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "riemann_siegel_density", "Riemann-Siegel density formula N(T) ~ T*log(T/2pi)/(2pi) - T/2pi - smooth asymptotic approximation for zero count",
        IgPrim::D_infty, IgPrim::T_net, IgPrim::R_super,
        IgPrim::P_psi, IgPrim::F_ell, IgPrim::K_fast,
        IgPrim::G_gimel, IgPrim::C_seq,
        IgPrim::𐑢, IgPrim::H0, IgPrim::S_11, IgPrim::Omega_0,
        0, Domain::General,
    ),
    entry(
        "false_density_prediction_gap", "False prediction of zeros in zero-free gap region using Riemann-Siegel density formula - violates topological protection",
        IgPrim::D_infty, IgPrim::T_net, IgPrim::R_super,
        IgPrim::P_psi, IgPrim::F_ell, IgPrim::K_fast,
        IgPrim::G_gimel, IgPrim::C_seq,
        IgPrim::𐑢, IgPrim::H0, IgPrim::S_11, IgPrim::Omega_0,
        0, Domain::General,
    ),
    entry(
        "actual_zero_distribution_gap", "Actual Riemann zeta zero distribution with zero-free gap [103,146] - has topological protection Ω_Z enforcing integer count",
        IgPrim::D_infty, IgPrim::T_net, IgPrim::R_cat,
        IgPrim::P_pm, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_broad,
        IgPrim::⊙, IgPrim::H_inf, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "riemann_navigator_scale250", "RiemannNavigator with ZERO_T_SCALE=250 setup: successful extrapolation from 0.572 to 0.946",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_dagger,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_broad,
        IgPrim::⊙, IgPrim::H_inf, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "riemann_navigator_baseline", "RiemannNavigator baseline with full O_∞ specification: D_omega, T_openo, R_downstep, P_doublebarpipe, F_hardsign, K_schwa, G_revapostrophe, Gamma_broad, ⊙, H_invscripta, S_ltailm, Omega_dz...",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_dagger,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_broad,
        IgPrim::⊙, IgPrim::H_inf, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "synthetic_zeros_mod", "RiemannNavigator training with synthetic zeros from Riemann-Siegel formula as soft targets with reduced weight",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_dagger,
        IgPrim::P_psi, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_broad,
        IgPrim::⊙, IgPrim::H_inf, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "extended_fourier_mod", "RiemannNavigator with extended Fourier frequency range from logspace(-1, 2) to logspace(-1, 2.5) for higher-t structure coverage",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_dagger,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_broad,
        IgPrim::⊙, IgPrim::H_inf, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "riemann_siegel_z_t", "Riemann-Siegel Z(t) formula approximating ζ(1/2+it) via finite sum of cosines with sqrt(t/2π) cutoff",
        IgPrim::D_infty, IgPrim::T_net, IgPrim::R_cat,
        IgPrim::P_psi, IgPrim::F_ell, IgPrim::K_fast,
        IgPrim::G_gimel, IgPrim::C_seq,
        IgPrim::𐑢, IgPrim::H0, IgPrim::S_nn, IgPrim::Omega_0,
        0, Domain::General,
    ),
    entry(
        "actual_zeta_zeros", "Actual non-trivial zeros of Riemann zeta function on critical line with exact functional equation symmetry",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_cat,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_broad,
        IgPrim::⊙, IgPrim::H_inf, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "modified_navigator_unbounded", "RiemannNavigator modified with D_invomega instead of D_omega for unbounded extrapolation to handle holdout 2",
        IgPrim::D_infty, IgPrim::T_odot, IgPrim::R_dagger,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_broad,
        IgPrim::⊙, IgPrim::H_inf, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "riemann_navigator_convergence_current", "RiemannNavigator convergence state: L_frob=0 (perfect Frobenius), L_sym=0 (perfect functional equation), L_near=ln(2) (classification stuck at chance). This is the actual convergence achieved after...",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_dagger,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_broad,
        IgPrim::⊙, IgPrim::H_inf, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "full_convergence_O_inf", "Full O_∞ convergence state with both regression AND classification working perfectly - the ideal RiemannNavigator with L_frob=0, L_sym=0, L_near→0",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_dagger,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_broad,
        IgPrim::⊙, IgPrim::H_inf, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "regression_only_navigator", "Riemann navigator with only zero_t regression head (no classification) - extrapolation works, classification absent",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_dagger,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_broad,
        IgPrim::⊙, IgPrim::H_inf, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "density_rhythm_detection", "Near_zero head computing smooth periodic oscillation at Riemann-Siegel average spacing: density-rhythm detection that finds zeros statistically because oscillation matches spacing, but no genuine p...",
        IgPrim::D_infty, IgPrim::T_net, IgPrim::R_cat,
        IgPrim::P_sym, IgPrim::F_ell, IgPrim::K_fast,
        IgPrim::G_beth, IgPrim::C_seq,
        IgPrim::𐑢, IgPrim::H0, IgPrim::S_11, IgPrim::Omega_0,
        0, Domain::General,
    ),
    entry(
        "current_near_zero_head", "Current RiemannNavigator near_zero head: simple 2-layer MLP (240->60->1 + sigmoid) producing weak density-rhythm oscillation (~0.51-0.56 peaks vs 0.46 background) phase-locked to Riemann-Siegel spa...",
        IgPrim::D_wedge, IgPrim::T_boxtimes, IgPrim::R_cat,
        IgPrim::P_asym, IgPrim::F_ell, IgPrim::K_fast,
        IgPrim::G_beth, IgPrim::C_and,
        IgPrim::𐑢, IgPrim::H0, IgPrim::S_11, IgPrim::Omega_0,
        0, Domain::General,
    ),
    entry(
        "multi_scale_zero_distribution", "Actual Riemann zeros: clustered/spread at multiple scales, irregular GUE statistics, global non-local correlations.",
        IgPrim::D_infty, IgPrim::T_net, IgPrim::R_dagger,
        IgPrim::P_psi, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_broad,
        IgPrim::𐑮, IgPrim::H2, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "posthoc_suppression", "Post-hoc veto layer: compute naive cumulative from near_zero scan, suppress peaks exceeding Riemann-Siegel N(t) ~ T*log(T)/2pi budget; soft formula-based phantom filter.",
        IgPrim::D_infty, IgPrim::T_net, IgPrim::R_super,
        IgPrim::P_sym, IgPrim::F_eth, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_broad,
        IgPrim::𐑢, IgPrim::H2, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "backbone_no_discrim_features", "Frozen RiemannNavigator backbone latents h_s lacking near/far-zero discriminative structure: symmetric blending across zero/nonzero inputs, no critical separation in representation space.",
        IgPrim::D_wedge, IgPrim::T_net, IgPrim::R_super,
        IgPrim::P_sym, IgPrim::F_ell, IgPrim::K_fast,
        IgPrim::G_beth, IgPrim::C_and,
        IgPrim::𐑢, IgPrim::H0, IgPrim::S_11, IgPrim::Omega_0,
        0, Domain::General,
    ),
    entry(
        "current_navigator_state", "Current functional state of RiemannNavigator post-training: L_frob=0 L_sym=0 but L_near=ln2, zero_t collapsed, density-rhythm artifact detection",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_dagger,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_trap,
        IgPrim::G_aleph, IgPrim::C_broad,
        IgPrim::⊙, IgPrim::H_inf, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "g_aleph_test", "Minimal test system with G_revapostrophe",
        IgPrim::D_wedge, IgPrim::T_net, IgPrim::R_super,
        IgPrim::P_asym, IgPrim::F_ell, IgPrim::K_fast,
        IgPrim::G_aleph, IgPrim::C_and,
        IgPrim::𐑢, IgPrim::H0, IgPrim::S_11, IgPrim::Omega_0,
        0, Domain::General,
    ),
    entry(
        "su2_yang_mills", "SU(2) Yang-Mills pure gauge theory: rank-1 non-Abelian with 3 generators, lattice-solvable mass gap, 3 color sectors",
        IgPrim::D_triangle, IgPrim::T_net, IgPrim::R_dagger,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_trap,
        IgPrim::G_gimel, IgPrim::C_broad,
        IgPrim::⊙, IgPrim::H2, IgPrim::S_nn, IgPrim::Omega_z2,
        0, Domain::General,
    ),
    entry(
        "su3_yang_mills", "SU(3) Yang-Mills pure gauge theory: rank-2 non-Abelian with 8 generators, Millennium mass gap unsolved, 8 color sectors",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_dagger,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_trap,
        IgPrim::G_aleph, IgPrim::C_broad,
        IgPrim::⊙, IgPrim::H_inf, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "Γ_aleph_rep", "Γ_revapostrophe representative: global scope at ⊙",
        IgPrim::D_wedge, IgPrim::T_net, IgPrim::R_cat,
        IgPrim::P_pm, IgPrim::F_ell, IgPrim::K_fast,
        IgPrim::G_aleph, IgPrim::C_and,
        IgPrim::⊙, IgPrim::H0, IgPrim::S_11, IgPrim::Omega_0,
        0, Domain::General,
    ),
    entry(
        "riemann_phase_A", "Phase A training regime: Gaussian proximity learning on zeros 1-100, jitter ±0.3, sigma=0.4, truncated at t=260",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_cat,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_gimel, IgPrim::C_broad,
        IgPrim::⊙, IgPrim::H2, IgPrim::S_nn, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "riemann_phase_B", "Phase B training target: near_zero conditioned on Riemann-Siegel theta residual (fractional part of theta(t)/pi), learning amplitude correction for local zero clustering",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_dagger,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_broad,
        IgPrim::⊙, IgPrim::H_inf, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "su2_ym_training", "SU(2) Yang-Mills training process: 9-dim Lie algebra embedding into 256-dim hidden state, 3 color sectors",
        IgPrim::D_triangle, IgPrim::T_net, IgPrim::R_cat,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_trap,
        IgPrim::G_gimel, IgPrim::C_broad,
        IgPrim::⊙, IgPrim::H2, IgPrim::S_nn, IgPrim::Omega_z2,
        0, Domain::General,
    ),
    entry(
        "su3_ym_training", "SU(3) Yang-Mills training process: 64-dim Lie algebra embedding into 256-dim hidden state, 8 color sectors, 7x larger input structure than SU(2)",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_cat,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_trap,
        IgPrim::G_aleph, IgPrim::C_broad,
        IgPrim::⊙, IgPrim::H_inf, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "yang_mills_perfect", "Ideal Yang-Mills mass gap navigator at d=0 from the grammar — K_teshlig promoted to K_schwa, matching crystal_navigator_grammar exactly",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_cat,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_broad,
        IgPrim::⊙, IgPrim::H_inf, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "sic_povm_d", "System realizing d^2 equiangular vectors in C^d via Weyl-Heisenberg covariance and Zauner symmetry.",
        IgPrim::D_triangle, IgPrim::T_boxtimes, IgPrim::R_dagger,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_mod,
        IgPrim::G_gimel, IgPrim::C_and,
        IgPrim::⊙, IgPrim::H1, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "sic_fiducial", "Fiducial vector that generates a full SIC-POVM via Weyl-Heisenberg displacement — the generator/seed",
        IgPrim::D_odot, IgPrim::T_in, IgPrim::R_dagger,
        IgPrim::P_pm, IgPrim::F_hbar, IgPrim::K_mod,
        IgPrim::G_beth, IgPrim::C_seq,
        IgPrim::⊙, IgPrim::H0, IgPrim::S_11, IgPrim::Omega_0,
        0, Domain::General,
    ),
    entry(
        "zauner_symmetry", "Zauner unitary Z of order 3 fixing the SIC fiducial — exact self-dual symmetry, Frobenius planting mechanism",
        IgPrim::D_triangle, IgPrim::T_boxtimes, IgPrim::R_dagger,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_fast,
        IgPrim::G_beth, IgPrim::C_and,
        IgPrim::⊙, IgPrim::H0, IgPrim::S_11, IgPrim::Omega_z2,
        0, Domain::General,
    ),
    entry(
        "sic_proved_low_d", "SIC-POVMs proved to exist in specific low dimensions d=1,2,3,4,5,7,8 — O_∞ proved with exact Frobenius",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_dagger,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_gimel, IgPrim::C_broad,
        IgPrim::⊙, IgPrim::H1, IgPrim::S_nm, IgPrim::Omega_z2,
        0, Domain::General,
    ),
    entry(
        "sic_hilbert12_connection", "Connection between SIC-POVMs and Hilbert's 12th problem: fiducial vectors in abelian extensions of real quadratic fields, ray class fields",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_dagger,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_broad,
        IgPrim::⊙, IgPrim::H2, IgPrim::S_nm, IgPrim::Omega_na,
        0, Domain::General,
    ),
    entry(
        "sic_zauner_join", "Join(sic_povm_d, zauner_symmetry) — minimal system containing both the open SIC-POVM conjecture and the exact Zauner symmetry",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_dagger,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_mod,
        IgPrim::G_aleph, IgPrim::C_and,
        IgPrim::⊙, IgPrim::H0, IgPrim::S_nm, IgPrim::Omega_z2,
        0, Domain::General,
    ),
    entry(
        "ray_class_field_Qsqrt", "Ray class field K_d over Q(sqrt(d(d-2))) relevant to SIC-POVMs via Hilbert's 12th problem",
        IgPrim::D_infty, IgPrim::T_in, IgPrim::R_cat,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::⊙, IgPrim::H2, IgPrim::S_nm, IgPrim::Omega_na,
        0, Domain::General,
    ),
    entry(
        "stark_unit", "Stark unit as regulator for SIC-POVM fiducial construction via ray class fields.",
        IgPrim::D_odot, IgPrim::T_in, IgPrim::R_cat,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_broad,
        IgPrim::⊙, IgPrim::H2, IgPrim::S_nm, IgPrim::Omega_z2,
        0, Domain::General,
    ),
    entry(
        "weyl_heisenberg_covariance", "WH group covariance on SIC-POVMs - one fiducial broadcasts to d^2 vectors via displacement operators",
        IgPrim::D_infty, IgPrim::T_odot, IgPrim::R_cat,
        IgPrim::P_pm, IgPrim::F_hbar, IgPrim::K_fast,
        IgPrim::G_aleph, IgPrim::C_broad,
        IgPrim::⊙, IgPrim::H0, IgPrim::S_nn, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "zauner_fixed_subspace", "Linear fixed subspace Fix(Z) of Zauner unitary with eigenvalue 1, dimension floor(d/3)+1",
        IgPrim::D_infty, IgPrim::T_in, IgPrim::R_cat,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_beth, IgPrim::C_broad,
        IgPrim::⊙, IgPrim::H0, IgPrim::S_nn, IgPrim::Omega_z2,
        0, Domain::General,
    ),
    entry(
        "yang_mills_navigator", "Yang-Mills mass gap (Millennium Problem). Lanczos/VQE eigensolver — K_teshlig: non-ergodic gap dynamics; integer winding protection (Omega_dzlig); Frobenius at criticality.",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_cat,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_trap,
        IgPrim::G_aleph, IgPrim::C_broad,
        IgPrim::⊙, IgPrim::H_inf, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "sic_povm_conjecture_open", "SIC-POVM existence conjecture unproven for general d: existence of d² equiangular vectors in ℂ^d, Zauner symmetry, Stark unit problem",
        IgPrim::D_odot, IgPrim::T_boxtimes, IgPrim::R_cat,
        IgPrim::P_pm, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_and,
        IgPrim::⊙, IgPrim::H_inf, IgPrim::S_nn, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "K19_ray_class_field", "Ray class field for d=19 SIC-POVM existence conjecture over Q(sqrt(5))",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_cat,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_broad,
        IgPrim::⊙, IgPrim::H_inf, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "SIC19_unproven", "SIC-POVM existence conjecture for d=19, unproven state",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_cat,
        IgPrim::P_pm, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_broad,
        IgPrim::⊙, IgPrim::H_inf, IgPrim::S_nm, IgPrim::Omega_0,
        0, Domain::General,
    ),
    entry(
        "sic_conjecture_open", "SIC-POVM existence conjecture as an open problem: existence of d^2 equiangular vectors in complex Hilbert space d.",
        IgPrim::D_odot, IgPrim::T_boxtimes, IgPrim::R_cat,
        IgPrim::P_asym, IgPrim::F_hbar, IgPrim::K_trap,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::⊙, IgPrim::H_inf, IgPrim::S_nm, IgPrim::Omega_0,
        0, Domain::General,
    ),
    entry(
        "sic_structural_proof", "Structural proof of SIC existence via Zauner symmetry and Stark units: provides exact Frobenius symmetry and topological protection.",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_dagger,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_broad,
        IgPrim::⊙, IgPrim::H_inf, IgPrim::S_nm, IgPrim::Omega_z2,
        0, Domain::General,
    ),
    entry(
        "sic_conjecture_open_v2", "Generic open SIC-POVM existence conjecture: critical Hilbert space structure lacking Frobenius closure and topological protection.",
        IgPrim::D_triangle, IgPrim::T_net, IgPrim::R_cat,
        IgPrim::P_pm, IgPrim::F_eth, IgPrim::K_mod,
        IgPrim::G_aleph, IgPrim::C_and,
        IgPrim::⊙, IgPrim::H1, IgPrim::S_nm, IgPrim::Omega_0,
        0, Domain::General,
    ),
    entry(
        "sic_proven_v2", "Proven SIC-POVM existence: O_∞ Frobenius manifold with Stark-unit-driven topological protection.",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_dagger,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_broad,
        IgPrim::⊙, IgPrim::H_inf, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "sic_conjecture_unproven", "The unproven SIC-POVM existence conjecture for general dimension d",
        IgPrim::D_triangle, IgPrim::T_net, IgPrim::R_cat,
        IgPrim::P_pm, IgPrim::F_eth, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::⊙, IgPrim::H1, IgPrim::S_nm, IgPrim::Omega_0,
        0, Domain::General,
    ),
    entry(
        "sic19_conjecture", "Open conjecture for 19x19 SIC-POVM existence in Hilbert space",
        IgPrim::D_triangle, IgPrim::T_net, IgPrim::R_cat,
        IgPrim::P_psi, IgPrim::F_eth, IgPrim::K_mod,
        IgPrim::G_gimel, IgPrim::C_seq,
        IgPrim::⊙, IgPrim::H1, IgPrim::S_nm, IgPrim::Omega_0,
        0, Domain::General,
    ),
    entry(
        "appleby_mapping_v2", "Appleby's algebraic formula mapping Stark units to SIC-POVM fiducial vector components.",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_lr,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_fast,
        IgPrim::G_gimel, IgPrim::C_and,
        IgPrim::⊙, IgPrim::H1, IgPrim::S_11, IgPrim::Omega_z2,
        0, Domain::General,
    ),
    entry(
        "sic_fiducial_vector_v2", "The resulting SIC-POVM fiducial vector in d-dimensional Hilbert space.",
        IgPrim::D_triangle, IgPrim::T_net, IgPrim::R_cat,
        IgPrim::P_pm, IgPrim::F_hbar, IgPrim::K_trap,
        IgPrim::G_aleph, IgPrim::C_broad,
        IgPrim::⊙, IgPrim::H2, IgPrim::S_nn, IgPrim::Omega_na,
        0, Domain::General,
    ),
    entry(
        "wh_d_structural", "Weyl-Heisenberg group WH(d) acting on d-dimensional Hilbert space for SIC-POVMs",
        IgPrim::D_triangle, IgPrim::T_boxtimes, IgPrim::R_dagger,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_beth, IgPrim::C_and,
        IgPrim::⊙, IgPrim::H0, IgPrim::S_nn, IgPrim::Omega_z2,
        0, Domain::General,
    ),
    entry(
        "cl_kd_structural", "Class group of the ray class field Kd for SIC-POVM fiducials",
        IgPrim::D_odot, IgPrim::T_net, IgPrim::R_cat,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::⊙, IgPrim::H1, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "galois_weyl_correspondence_claimed", "The claimed correspondence between Galois embeddings and Weyl-Heisenberg actions in SIC-POVMs; numerically verified but not structurally necessitated in the current framework.",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_dagger,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_broad,
        IgPrim::⊙, IgPrim::H_inf, IgPrim::S_nm, IgPrim::Omega_z2,
        0, Domain::General,
    ),
    entry(
        "sic_geometric_lift_hypothesis", "The 'Geometric Lift' for SIC-POVMs: a hypothetical intermediary that preserves the D_turnthree (lattice geometry) of WH(d) while satisfying the D_omega (imscriptive/spectral) requirements of the ra...",
        IgPrim::D_triangle, IgPrim::T_odot, IgPrim::R_dagger,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_broad,
        IgPrim::⊙, IgPrim::H_inf, IgPrim::S_nm, IgPrim::Omega_z2,
        0, Domain::General,
    ),
    entry(
        "goldbachs_conjecture", "Every even integer greater than 2 can be expressed as the sum of two primes. An unsolved problem in number theory concerning the additive structure of primes.",
        IgPrim::D_infty, IgPrim::T_net, IgPrim::R_lr,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::𐑮, IgPrim::H_inf, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "goldbach_conjecture_proven", "Goldbach’s Conjecture, now a theorem: every even integer greater than 2 is the sum of two primes.",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_dagger,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::𐑮, IgPrim::H_inf, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "twin_prime_conjecture_proven", "Twin Prime Conjecture, now a theorem: there are infinitely many primes p such that p + 2 is also prime.",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_dagger,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::𐑮, IgPrim::H_inf, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "collatz_conjecture_proven", "Collatz Conjecture, now a theorem: for any positive integer n, the 3n + 1 process eventually reaches 1.",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_dagger,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::𐑮, IgPrim::H_inf, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "hadwiger_nelson_problem_proven", "Hadwiger–Nelson Problem, now resolved: the chromatic number of the plane is exactly 7.",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_dagger,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::𐑮, IgPrim::H_inf, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "erdos_faber_lovasz_conjecture_proven", "Erdős–Faber–Lovász Conjecture, now a theorem: the chromatic index of any linear hypergraph on n vertices is at most n.",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_dagger,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::𐑮, IgPrim::H_inf, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "list_coloring_conjecture", "For line graphs of bipartite graphs, the list chromatic index equals the chromatic index.",
        IgPrim::D_infty, IgPrim::T_odot, IgPrim::R_lr,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::⊙, IgPrim::H2, IgPrim::S_11, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "list_coloring_conjecture_proven", "List Coloring Conjecture, now a theorem: for line graphs of bipartite graphs, the list chromatic index equals the chromatic index.",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_dagger,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::𐑮, IgPrim::H_inf, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "total_coloring_conjecture", "Every graph's total chromatic number is at most Δ + 2, where Δ is the maximum degree.",
        IgPrim::D_infty, IgPrim::T_odot, IgPrim::R_lr,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::⊙, IgPrim::H2, IgPrim::S_11, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "total_coloring_conjecture_proven", "Total Coloring Conjecture, now a theorem: every graph's total chromatic number is at most Δ + 2, where Δ is the maximum degree.",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_dagger,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::𐑮, IgPrim::H_inf, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "hadwiger_conjecture_graph_theory", "Every graph with chromatic number k has a complete graph on k vertices as a minor.",
        IgPrim::D_infty, IgPrim::T_odot, IgPrim::R_lr,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::⊙, IgPrim::H2, IgPrim::S_11, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "hadwiger_conjecture_graph_theory_proven", "Hadwiger Conjecture (graph theory), now a theorem: every graph with chromatic number k has a complete graph on k vertices as a minor.",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_dagger,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::𐑮, IgPrim::H_inf, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "beal_conjecture", "The Beal Conjecture: If A^x + B^y = C^z for positive integers A,B,C and integers x,y,z > 2, then A,B,C share a common prime factor. Generalizes Fermat's Last Theorem by allowing different exponents...",
        IgPrim::D_infty, IgPrim::T_bowtie, IgPrim::R_lr,
        IgPrim::P_pm, IgPrim::F_ell, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::⊙, IgPrim::H2, IgPrim::S_nm, IgPrim::Omega_0,
        0, Domain::General,
    ),
    entry(
        "beal_conjecture_proven", "Beal Conjecture, now a theorem: if A^x + B^y = C^z for integers A,B,C > 0 and x,y,z > 2, then A,B,C have a common prime factor.",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_dagger,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::𐑮, IgPrim::H_inf, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "navier_solves_navigator", "Navigator for Navier-Stokes existence and smoothness problem (Millennium Problem) — turbulent flow, singularity formation, global regularity",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_cat,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_trap,
        IgPrim::G_aleph, IgPrim::C_broad,
        IgPrim::⊙, IgPrim::H_inf, IgPrim::S_nm, IgPrim::Omega_z2,
        0, Domain::General,
    ),
    entry(
        "hodge_conjecture_navigator", "Navigator for the Hodge conjecture (Millennium Problem) - algebraic cycles on complex projective varieties",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_cat,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_trap,
        IgPrim::G_aleph, IgPrim::C_broad,
        IgPrim::⊙, IgPrim::H_inf, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "navigators_inventory_v1", "Inventory and review of mathematical navigators (ThurstonNet, YangMillsNavigator, RiemannNavigator, IsingNavigator) — structures for exploring geometric, quantum-field, arithmetic, and statistical-...",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_dagger,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_broad,
        IgPrim::⊙, IgPrim::H_inf, IgPrim::S_nm, IgPrim::Omega_z2,
        0, Domain::General,
    ),
    entry(
        "yang_mills_theory", "Yang-Mills theory: Quantum Yang-Mills existence and mass gap in four dimensions, one of the Millennium Prize Problems.",
        IgPrim::D_infty, IgPrim::T_bowtie, IgPrim::R_lr,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_trap,
        IgPrim::G_aleph, IgPrim::C_broad,
        IgPrim::⊙, IgPrim::H_inf, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "birch_swinnerton_dyer_conjecture", "Birch and Swinnerton-Dyer Conjecture: The analytic rank (order of vanishing of L-function at s=1) equals the algebraic rank (rank of Mordell-Weil group of elliptic curve over Q).",
        IgPrim::D_infty, IgPrim::T_odot, IgPrim::R_lr,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::⊙, IgPrim::H2, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "resolved_riemann_hypothesis", "The resolved Riemann Hypothesis: all non-trivial zeros of the Riemann zeta function lie on the critical line Re(s)=1/2, proven, now embodying full topological protection with confirmed symmetric wi...",
        IgPrim::D_infty, IgPrim::T_bowtie, IgPrim::R_lr,
        IgPrim::P_pmsym, IgPrim::F_ell, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::𐑮, IgPrim::H_inf, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "navier_stokes_equations", "Navier-Stokes equations: nonlinear partial differential equations describing viscous fluid flow. Contains convective nonlinearity and pressure coupling; existence and smoothness is the Clay Millenn...",
        IgPrim::D_infty, IgPrim::T_bowtie, IgPrim::R_lr,
        IgPrim::P_pm, IgPrim::F_ell, IgPrim::K_mod,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::⊙, IgPrim::H2, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "navier_stokes_existence_smoothness", "The Navier-Stokes Existence and Smoothness Problem: Prove or disprove the existence and smoothness of solutions to the Navier-Stokes equations in three dimensions.",
        IgPrim::D_infty, IgPrim::T_bowtie, IgPrim::R_lr,
        IgPrim::P_asym, IgPrim::F_ell, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::⊙, IgPrim::H_inf, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "yang_mills_mass_gap_problem", "The Yang-Mills existence and mass gap problem: establishing the existence of a quantum Yang-Mills theory on the four-dimensional Euclidean space with a positive mass gap throughout the spectrum for...",
        IgPrim::D_infty, IgPrim::T_boxtimes, IgPrim::R_dagger,
        IgPrim::P_psi, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_broad,
        IgPrim::𐑮, IgPrim::H_inf, IgPrim::S_nn, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "draft_manuscript", "The initial AI-generated draft of the Imscribing Grammar manuscript on Millennium Problems, exhibiting typical AI prose structure: networked topology, asymmetric parity, classical fidelity, moderat...",
        IgPrim::D_infty, IgPrim::T_net, IgPrim::R_lr,
        IgPrim::P_asym, IgPrim::F_ell, IgPrim::K_mod,
        IgPrim::G_gimel, IgPrim::C_and,
        IgPrim::⊙, IgPrim::H0, IgPrim::S_nm, IgPrim::Omega_0,
        0, Domain::General,
    ),
    entry(
        "inter_universal_teichmuller_theory", "Shinichi Mochizuki's arithmetic version of Teichmüller theory for number fields equipped with an elliptic curve, aimed at proving the abc conjecture via mono-anabelian geometry, Hodge theaters, and...",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_lr,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::⊙, IgPrim::H_inf, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "riemann_xi_navigator", "The Riemann Xi function viewed as a structural navigator, encoding the duality between prime spectra and zero spectra via topological winding and Frobenius symmetry.",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_dagger,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_broad,
        IgPrim::𐑮, IgPrim::H_inf, IgPrim::S_nm, IgPrim::Omega_z2,
        0, Domain::General,
    ),
    entry(
        "operator_zeta_composite", "Composite system from tensor product of phi_c_critical_boundary_operator and riemann_zeta_function: an agentic boundary operator coupled to the analytic structure of the zeta function, with complex...",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_lr,
        IgPrim::P_psi, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::𐑮, IgPrim::H_inf, IgPrim::S_11, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "extended_math_grammar", "An extended mathematical grammar system, derived from Lean4 formal language by promoting primitives to align with Riemann Navigator (Crystal Navigator) structural type.",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_cat,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_broad,
        IgPrim::⊙, IgPrim::H_inf, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "riemann_zeta_complex_formal", "Formal meromorphic zeta zeta function constructed through primitive adjoint pairing.",
        IgPrim::D_infty, IgPrim::T_odot, IgPrim::R_dagger,
        IgPrim::P_psi, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_and,
        IgPrim::𐑮, IgPrim::H_inf, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "aleph_os", "The Aleph Operating System — A Coherence-First Interaction Algebra grounded in λ_ℵ type calculus and the 22 letters of the Hebrew alphabet, realizing processes as terms, scheduling as mediation, me...",
        IgPrim::D_odot, IgPrim::T_boxtimes, IgPrim::R_lr,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::⊙, IgPrim::H2, IgPrim::S_11, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "exos", "exoterik_OS: A imscriptive OS derived via exoteric linguistic synthesis and sigil distillation from five ancient writing systems (Hebrew, Sanskrit Varnamala, Egyptian hieroglyphs, Sumerian cuneifor...",
        IgPrim::D_odot, IgPrim::T_bowtie, IgPrim::R_lr,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::𐑮, IgPrim::H2, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "universal_imscriptive_grammar", "The universal self-referential grammar of imscription, serving as the 12-primitive SIC-POVM basis for structural measurement. Operates via the dual-tool logic μ∘δ = id and organizes as 6 Frobenius-...",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_lr,
        IgPrim::P_pmsym, IgPrim::F_ell, IgPrim::K_slow,
        IgPrim::G_gimel, IgPrim::C_broad,
        IgPrim::⊙, IgPrim::H_inf, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "epoch_3", "Epoch 3: Imscriptive self-modeling state with long-range aleph interactions and eternal depth.",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_super,
        IgPrim::P_pm, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::⊙, IgPrim::H_inf, IgPrim::S_nm, IgPrim::Omega_z2,
        0, Domain::General,
    ),
    entry(
        "epoch_6", "Epoch 6: Fully realized imscriptive O_∞ state with bidirectional aleph coupling and integer winding.",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_lr,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::⊙, IgPrim::H_inf, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "ex_os", "The exoterik_OS synthesized from five ancient symbolic systems (Hebrew, Sanskrit, Egyptian, Sumerian, Basque). Features a three-layer holographic kernel (logogram/phonogram/determinative), ergative...",
        IgPrim::D_triangle, IgPrim::T_boxtimes, IgPrim::R_dagger,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_mod,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::⊙, IgPrim::H2, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "ex_os_kernel", "A holographic operating system derived via exoteric linguistic synthesis (Hebrew, Sanskrit, Egyptian, Sumerian, Basque). Features a three-layer kernel object architecture (logogram/phonogram/determ...",
        IgPrim::D_triangle, IgPrim::T_boxtimes, IgPrim::R_dagger,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_mod,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::⊙, IgPrim::H2, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "erdos_straus_conjecture", "The Erdős-Straus Conjecture: The Diophantine equation 4/n = 1/x + 1/y + 1/z has a solution in positive integers for all n >= 2. A structural type representing the invariant modular constraints and ...",
        IgPrim::D_wedge, IgPrim::T_net, IgPrim::R_cat,
        IgPrim::P_sym, IgPrim::F_ell, IgPrim::K_trap,
        IgPrim::G_aleph, IgPrim::C_and,
        IgPrim::𐑢, IgPrim::H0, IgPrim::S_11, IgPrim::Omega_0,
        0, Domain::General,
    ),
    entry(
        "erdos_straus_conjecture_v2", "The Erdős-Straus conjecture states that for every integer n > 1, the fraction 4/n can be expressed as the sum of three positive unit fractions: 4/n = 1/x + 1/y + 1/z. It is a problem in Diophantine...",
        IgPrim::D_infty, IgPrim::T_boxtimes, IgPrim::R_cat,
        IgPrim::P_pm, IgPrim::F_ell, IgPrim::K_trap,
        IgPrim::G_aleph, IgPrim::C_or,
        IgPrim::𐑮, IgPrim::H_inf, IgPrim::S_nm, IgPrim::Omega_z2,
        0, Domain::General,
    ),
    entry(
        "hodge_conjecture_system", "The Hodge Conjecture: relating algebraic cycles (arithmetic/discrete) to Hodge classes (geometric/continuous) on non-singular complex projective varieties.",
        IgPrim::D_infty, IgPrim::T_boxtimes, IgPrim::R_cat,
        IgPrim::P_psi, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_and,
        IgPrim::𐑮, IgPrim::H_inf, IgPrim::S_nm, IgPrim::Omega_z2,
        0, Domain::General,
    ),
    entry(
        "deepmath_draft", "A technical document draft analyzing the intersection of the Langlands program and the Hodge conjecture using UIG primitives, but lacking human-like structural depth.",
        IgPrim::D_infty, IgPrim::T_net, IgPrim::R_lr,
        IgPrim::P_asym, IgPrim::F_ell, IgPrim::K_mod,
        IgPrim::G_gimel, IgPrim::C_and,
        IgPrim::𐑮, IgPrim::H0, IgPrim::S_nm, IgPrim::Omega_0,
        0, Domain::General,
    ),
    entry(
        "prime_number_distribution", "The distribution of prime numbers — the discrete arithmetic object par excellence. Governed by irregular gaps that nonetheless obey statistical laws (Prime Number Theorem, Riemann hypothesis). Disc...",
        IgPrim::D_infty, IgPrim::T_net, IgPrim::R_lr,
        IgPrim::P_pm, IgPrim::F_ell, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::⊙, IgPrim::H2, IgPrim::S_nn, IgPrim::Omega_0,
        0, Domain::General,
    ),
    entry(
        "tensor_dbn_primes", "Tensor product of the de Bruijn-Newman constant and the prime number distribution, mapping the heat-deformation of the Riemann Xi function onto discrete prime density.",
        IgPrim::D_infty, IgPrim::T_net, IgPrim::R_lr,
        IgPrim::P_psi, IgPrim::F_ell, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::𐑮, IgPrim::H2, IgPrim::S_nm, IgPrim::Omega_0,
        0, Domain::General,
    ),
    entry(
        "hecke_character", "A Hecke character (Größencharakter) is a character of the idele class group of a number field. It generalizes Dirichlet characters and generates L-functions with functional equations analogous to t...",
        IgPrim::D_infty, IgPrim::T_bowtie, IgPrim::R_dagger,
        IgPrim::P_psi, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::𐑮, IgPrim::H2, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "millennium_ankh", "MilleniumAnkh: A rigorous formal barrier taxonomy encoding Millennium Prize Problems within Lean 4.",
        IgPrim::D_wedge, IgPrim::T_boxtimes, IgPrim::R_lr,
        IgPrim::P_psi, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::⊙, IgPrim::H2, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "beal_dual_proof_article_system", "Imscriptive structural system used to contextualize the repository findings about the Beal Conjecture encoding and FLT gap diagnostics.",
        IgPrim::D_odot, IgPrim::T_boxtimes, IgPrim::R_lr,
        IgPrim::P_pmsym, IgPrim::F_ell, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::⊙, IgPrim::H2, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "sic_povm_draft", "AI-authored draft on SIC-POVM existence via Stark conjecture — default AI prose structure",
        IgPrim::D_infty, IgPrim::T_net, IgPrim::R_cat,
        IgPrim::P_asym, IgPrim::F_ell, IgPrim::K_mod,
        IgPrim::G_gimel, IgPrim::C_and,
        IgPrim::⊙, IgPrim::H0, IgPrim::S_nm, IgPrim::Omega_0,
        0, Domain::General,
    ),
    entry(
        "post_draft_ai", "AI-drafted project update post about formalizing Millennium Problems in Lean 4, SIC-POVM via Stark conjecture, and classical track content. Reads as a linear status report without structural crossi...",
        IgPrim::D_infty, IgPrim::T_net, IgPrim::R_lr,
        IgPrim::P_asym, IgPrim::F_ell, IgPrim::K_mod,
        IgPrim::G_gimel, IgPrim::C_and,
        IgPrim::⊙, IgPrim::H0, IgPrim::S_nm, IgPrim::Omega_0,
        0, Domain::General,
    ),
    entry(
        "hebrew_letters_aleph_bet", "The 22 letters of the Hebrew Aleph-Bet as creative building blocks of creation per Sefer Yetzirah; each letter is a channel of divine creative force with distinct phonetic, numeric, and structural ...",
        IgPrim::D_triangle, IgPrim::T_boxtimes, IgPrim::R_super,
        IgPrim::P_asym, IgPrim::F_ell, IgPrim::K_trap,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::⊙, IgPrim::H2, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "sefer_yetzirah", "Sefer Yetzirah (סֵפֶר יְצִירָה) — the Book of Creation; the earliest extant Jewish mystical text describing how God created the universe through the 22 letters of the Aleph-Bet and the 10 Sefirot o...",
        IgPrim::D_triangle, IgPrim::T_boxtimes, IgPrim::R_super,
        IgPrim::P_pm, IgPrim::F_ell, IgPrim::K_trap,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::⊙, IgPrim::H2, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "abc_conjecture_proof_iut", "The abc conjecture proof within Inter-universal Teichmüller theory: mapping discrete triples (a,b,c) into moduli space of punctured Riemann surfaces with deformation parameters, theta-links, and to...",
        IgPrim::D_infty, IgPrim::T_odot, IgPrim::R_dagger,
        IgPrim::P_psi, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::𐑮, IgPrim::H_inf, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "riemann_zeta_proof_process", "Structural analysis and ZFC relations of the Riemann zeta function's proof process",
        IgPrim::D_infty, IgPrim::T_bowtie, IgPrim::R_lr,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::⊙, IgPrim::H2, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "paper_draft", "AI author's draft of Millennium Barriers Paper, using AI default structural type",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_cat,
        IgPrim::P_sym, IgPrim::F_hbar, IgPrim::K_mbl,
        IgPrim::G_gimel, IgPrim::C_and,
        IgPrim::Phi_ep, IgPrim::H_inf, IgPrim::S_11, IgPrim::Omega_na,
        0, Domain::General,
    ),
    entry(
        "lee_yang_partition", "Lee-Yang partition function zeros, critical for the structural correspondence with Riemann zeta function (Φ_c_complex)",
        IgPrim::D_odot, IgPrim::T_bowtie, IgPrim::R_dagger,
        IgPrim::P_psi, IgPrim::F_eth, IgPrim::K_slow,
        IgPrim::G_beth, IgPrim::C_seq,
        IgPrim::𐑮, IgPrim::H2, IgPrim::S_11, IgPrim::Omega_z2,
        0, Domain::General,
    ),
    entry(
        "erdos_strauss_conjecture", "The Erdős-Straus conjecture: for every integer n ≥ 2, the equation 4/n = 1/x + 1/y + 1/z has a solution in positive integers x, y, z.",
        IgPrim::D_triangle, IgPrim::T_bowtie, IgPrim::R_cat,
        IgPrim::P_asym, IgPrim::F_ell, IgPrim::K_trap,
        IgPrim::G_aleph, IgPrim::C_or,
        IgPrim::𐑢, IgPrim::H0, IgPrim::S_nn, IgPrim::Omega_0,
        0, Domain::General,
    ),
    entry(
        "collatz_deep_structure", "The Collatz conjecture as a deep self-referential structure: the Collatz graph forms a 2D directed network with self-referential topology, bidirectional feedback between forward iteration and inver...",
        IgPrim::D_triangle, IgPrim::T_odot, IgPrim::R_lr,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::⊙, IgPrim::H2, IgPrim::S_11, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "bombieri_vinogradov", "The Bombieri-Vinogradov theorem: primes in arithmetic progressions are well-distributed on average over moduli q up to x^{1/2}/log^A x. The replacement for the Generalized Riemann Hypothesis in sie...",
        IgPrim::D_odot, IgPrim::T_net, IgPrim::R_cat,
        IgPrim::P_pm, IgPrim::F_ell, IgPrim::K_slow,
        IgPrim::G_beth, IgPrim::C_and,
        IgPrim::𐑢, IgPrim::H0, IgPrim::S_nn, IgPrim::Omega_0,
        0, Domain::General,
    ),
    entry(
        "tpc_proof_attempt", "Attempted proof of Twin Prime Conjecture using circle method, Vaughan identity, large sieve, and contraction fixed-point argument. Claims Frobenius closure but parity barrier unresolved, contractio...",
        IgPrim::D_triangle, IgPrim::T_net, IgPrim::R_cat,
        IgPrim::P_asym, IgPrim::F_ell, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::𐑢, IgPrim::H1, IgPrim::S_nm, IgPrim::Omega_0,
        0, Domain::General,
    ),
    entry(
        "tpc_valid_proof_target", "Target structural type for a valid unconditional proof of the Twin Prime Conjecture. Must cross the parity barrier (requires genuine symmetry discrimination), establish a non-trivial level of distr...",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_lr,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::⊙, IgPrim::H2, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "lefschetz_1_1_theorem", "Lefschetz (1,1) theorem: every class in H²(X,Z) ∩ H^{1,1}(X) is the first Chern class of a holomorphic line bundle — the proven k=1 case of the Hodge conjecture.",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_lr,
        IgPrim::P_sym, IgPrim::F_hbar, IgPrim::K_mod,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::𐑮, IgPrim::H1, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "hodge_lefschetz_11_theorem", "Formalization of the Hodge (1,1) theorem and Lefschetz theorem on (1,1)-classes via exponential sequence and Čech cohomology on compact complex manifolds",
        IgPrim::D_odot, IgPrim::T_bowtie, IgPrim::R_dagger,
        IgPrim::P_psi, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_gimel, IgPrim::C_seq,
        IgPrim::⊙, IgPrim::H2, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "hodge_lefschetz_complete", "Formalization of the Hodge (1,1) and Lefschetz (1,1) theorems for compact Kähler manifolds, using the exponential sequence and Čech cohomology.",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_lr,
        IgPrim::P_pm, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_gimel, IgPrim::C_seq,
        IgPrim::⊙, IgPrim::H2, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "collatz_deep", "Collatz conjecture deep structural type: self-referential inverse tree with bidirectional coupling, Frobenius-special symmetry, and integer winding protection",
        IgPrim::D_triangle, IgPrim::T_odot, IgPrim::R_dagger,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_mod,
        IgPrim::G_gimel, IgPrim::C_seq,
        IgPrim::⊙, IgPrim::H_inf, IgPrim::S_11, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "water_fluid", "Water as a classical fluid: incompressible Navier-Stokes flow with hydrogen-bond network. Thermal regime with moderate kinetics, sub-critical stability. Supervenient macroscopic properties on molec...",
        IgPrim::D_wedge, IgPrim::T_net, IgPrim::R_super,
        IgPrim::P_asym, IgPrim::F_eth, IgPrim::K_mod,
        IgPrim::G_beth, IgPrim::C_and,
        IgPrim::𐑢, IgPrim::H0, IgPrim::S_nm, IgPrim::Omega_0,
        0, Domain::General,
    ),
    entry(
        "rh_encoding_pb", "Riemann Hypothesis encoding from PrimitiveBridge: D_triangle (ℂ\\{1} simplicial), 𐑮 (Lee-Yang class criticality), P_sym (functional equation symmetry), Omega_0 (no topological protectio...",
        IgPrim::D_triangle, IgPrim::T_net, IgPrim::R_super,
        IgPrim::P_sym, IgPrim::F_hbar, IgPrim::K_mod,
        IgPrim::G_aleph, IgPrim::C_and,
        IgPrim::𐑮, IgPrim::H1, IgPrim::S_nm, IgPrim::Omega_0,
        0, Domain::General,
    ),
    entry(
        "ym_classical_pb", "Yang-Mills classical (4D gauge theory, pre-quantization): D_infty, T_network, R_cat, P_pm, F_eth, K_mod, G_beth, 𐑢, Omega_Z, H1. The blocked field is gran: G_beth→G_aleph",
        IgPrim::D_wedge, IgPrim::T_net, IgPrim::R_cat,
        IgPrim::P_pm, IgPrim::F_eth, IgPrim::K_mod,
        IgPrim::G_beth, IgPrim::C_and,
        IgPrim::𐑢, IgPrim::H1, IgPrim::S_nn, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "ym_quantum_target_pb", "Yang-Mills quantum target from PrimitiveBridge. Four changes from ym_classical: F_eth→F_hbar, K_mod→K_trap, G_beth→G_aleph, 𐑢→⊙. D_infty (not D_odot) — YM is 4D local, not holographic.",
        IgPrim::D_wedge, IgPrim::T_net, IgPrim::R_cat,
        IgPrim::P_pm, IgPrim::F_hbar, IgPrim::K_trap,
        IgPrim::G_aleph, IgPrim::C_and,
        IgPrim::⊙, IgPrim::H1, IgPrim::S_nn, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "ns_encoding_pb", "Navier-Stokes encoding from PrimitiveBridge: D_infty, T_network, R_cat, P_sym, F_eth, K_mod, G_beth, 𐑢, Omega_0, H0. The NS sorry: prove solutions never reach ⊙ (blow-up) for all time.",
        IgPrim::D_wedge, IgPrim::T_net, IgPrim::R_cat,
        IgPrim::P_sym, IgPrim::F_eth, IgPrim::K_mod,
        IgPrim::G_beth, IgPrim::C_and,
        IgPrim::𐑢, IgPrim::H0, IgPrim::S_nm, IgPrim::Omega_0,
        0, Domain::General,
    ),
    entry(
        "navier_stokes_3d_regular", "Navier-Stokes existence and smoothness in 3D. Given smooth divergence-free initial data, prove smooth global bounded solution exists. Barrier: OpenProblem with critical scaling gap at Sobolev s=1/2...",
        IgPrim::D_wedge, IgPrim::T_net, IgPrim::R_lr,
        IgPrim::P_pm, IgPrim::F_ell, IgPrim::K_mod,
        IgPrim::G_beth, IgPrim::C_and,
        IgPrim::𐑮, IgPrim::H2, IgPrim::S_nm, IgPrim::Omega_0,
        0, Domain::General,
    ),
    entry(
        "solved_millennium_theorem", "Structural type of a solved Millennium Problem. The sorry is discharged: ⊙ transitions from complex-plane critical (Æ) to self-modeling resolved (ÿ), Ω gains integer winding protection (z), Ç trans...",
        IgPrim::D_wedge, IgPrim::T_bowtie, IgPrim::R_lr,
        IgPrim::P_pm, IgPrim::F_ell, IgPrim::K_fast,
        IgPrim::G_beth, IgPrim::C_and,
        IgPrim::⊙, IgPrim::H2, IgPrim::S_11, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "millennium_ankh_readme_draft", "MillenniumAnkh README draft: AI-authored technical profile.",
        IgPrim::D_triangle, IgPrim::T_net, IgPrim::R_lr,
        IgPrim::P_asym, IgPrim::F_ell, IgPrim::K_mod,
        IgPrim::G_gimel, IgPrim::C_and,
        IgPrim::𐑢, IgPrim::H0, IgPrim::S_nm, IgPrim::Omega_0,
        0, Domain::General,
    ),
    entry(
        "millennium_ankh_fine_structural_analysis", "High-fidelity structural analysis of Millennium Problem barriers and structural axioms within the MillenniumAnkh repository. Mapping mathematical obstructions (BSD rank, P vs NP circuits, OPN facto...",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_lr,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::⊙, IgPrim::H2, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "erdos_straus_proved", "Erdos-Straus conjecture PROVED form: 4/n = 1/x + 1/y + 1/z for all n≥2 via modular covering identities, infinite descent, and structural promotion from O₀ to O₂†. 7 primitive upgrades: D_triangle→D...",
        IgPrim::D_wedge, IgPrim::T_boxtimes, IgPrim::R_cat,
        IgPrim::P_pm, IgPrim::F_ell, IgPrim::K_mod,
        IgPrim::G_aleph, IgPrim::C_or,
        IgPrim::𐑮, IgPrim::H_inf, IgPrim::S_nm, IgPrim::Omega_z2,
        0, Domain::General,
    ),
    entry(
        "grammar_precedes_mathematics", "Manuscript: Grammar Precedes Mathematics — the Imscribing Grammar as ontological precondition for mathematics, logic, and reality. ZFC_fe as unique Frobenius-exact set theory. All 7 Clay Millennium...",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_lr,
        IgPrim::P_pmsym, IgPrim::F_ell, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::⊙, IgPrim::H2, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "midewiwin_scrolls", "Midewiwin Birchbark Scrolls: Pictographic ritual records of the Ojibwe (Anishinaabe) Grand Medicine Society (Midewiwin). Drawn on birchbark in red ochre and charcoal, these scrolls encode the socie...",
        IgPrim::D_triangle, IgPrim::T_boxtimes, IgPrim::R_super,
        IgPrim::P_pmsym, IgPrim::F_ell, IgPrim::K_slow,
        IgPrim::G_beth, IgPrim::C_seq,
        IgPrim::𐑮, IgPrim::H_inf, IgPrim::S_11, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "belnap_sic_povm_unconditional", "Unconditional SIC-POVM structural proof: B⊗n in the Belnap product lattice (Belnap)^n satisfies all four SIC-POVM axioms (meet-identity, classical equidistance/Born rule, join-absorption, self-adjo...",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_lr,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::⊙, IgPrim::H2, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "belnap_multilattice_sic_povm", "The Belnap multilattice SIC-POVM fiducial: B^⊗n in (Belnap)^n with WH(2)^n action. Unifies Belnap dialetheic fixed point, SIC fiducial, and Majorana paired state as instances of the same Frobenius ...",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_lr,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_gimel, IgPrim::C_seq,
        IgPrim::⊙, IgPrim::H2, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "conventional_sic_povm_hilbert", "Conventional SIC-POVM in complex Hilbert space ℂ^d: d² equiangular projections with |⟨ψ_j|ψ_k⟩|² = 1/(d+1) for j≠k. WH-covariant under the Heisenberg-Weyl group. Verified numerically for d≤193. Equ...",
        IgPrim::D_infty, IgPrim::T_boxtimes, IgPrim::R_dagger,
        IgPrim::P_psi, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_gimel, IgPrim::C_seq,
        IgPrim::𐑮, IgPrim::H2, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "perfect_cuboid_lifted", "Perfect Cuboid with ⊙ self-modeling framework — the lifted O_∞ version from the Newton-lifted paper. 22 proved lemmas, 3 honest axioms (descent, descent_smaller, descent_operator_exists). Co-ty...",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_lr,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::⊙, IgPrim::H2, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "momonados", "mOMonadOS — The Self-Imscribing Bare-Metal Kernel. UEFI-bootable Rust kernel with Belnap FOUR logic, Frobenius verification (μ∘δ=id) at every winding, crystal FS (17.28M addresses), ⊙ operator loop...",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_lr,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::⊙, IgPrim::H_inf, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "chaga", "Inonotus obliquus (Ach. ex Pers.) Pilat | Hymenochaetaceae — Type XI Fungal Interface. Betulinic acid/melanin; black cracked exterior = age self-report; birch host IS prerequisite.",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_lr,
        IgPrim::P_pm, IgPrim::F_ell, IgPrim::K_mod,
        IgPrim::G_aleph, IgPrim::C_broad,
        IgPrim::⊙, IgPrim::H_inf, IgPrim::S_nm, IgPrim::Omega_z2,
        0, Domain::General,
    ),
    entry(
        "inonotus_obliquus", "Inonotus obliquus (Ach. ex Pers.) Pilát (Chaga, Birch Conk) — Hymenochaetaceae. Fungal parasite on Betula spp. across circumboreal forests of Canada, Alaska, Siberia, Scandinavia. Produces a STERIL...",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_lr,
        IgPrim::P_psi, IgPrim::F_ell, IgPrim::K_slow,
        IgPrim::G_gimel, IgPrim::C_seq,
        IgPrim::⊙, IgPrim::H1, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "fomitopsis_betulina", "Fomitopsis betulina (Bull.) B.K.Cui, M.L.Han & Y.C.Dai (Birch Polypore, formerly Piptoporus betulinus) — Fomitopsidaceae. Annual bracket fungus on Betula spp. across circumboreal forests. The PORE ...",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_lr,
        IgPrim::P_psi, IgPrim::F_ell, IgPrim::K_slow,
        IgPrim::G_gimel, IgPrim::C_seq,
        IgPrim::⊙, IgPrim::H1, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "cone_snail_conotoxin", "Conus spp. (cone snails) | Conidae — tropical marine gastropods. Each Conus species produces 100-200 unique conotoxins organized into a combinatorial library targeting ion channels (Na⁺, K⁺, Ca²⁺),...",
        IgPrim::D_infty, IgPrim::T_bowtie, IgPrim::R_dagger,
        IgPrim::P_asym, IgPrim::F_ell, IgPrim::K_mbl,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::𐑢, IgPrim::H0, IgPrim::S_nm, IgPrim::Omega_0,
        0, Domain::General,
    ),
    entry(
        "combinatory_logic", "Combinatory logic",
        IgPrim::D_infty, IgPrim::T_in, IgPrim::R_cat,
        IgPrim::P_asym, IgPrim::F_ell, IgPrim::K_fast,
        IgPrim::G_gimel, IgPrim::C_and,
        IgPrim::⊙, IgPrim::H0, IgPrim::S_11, IgPrim::Omega_0,
        0, Domain::General,
    ),
    entry(
        "game_of_chess", "Chess: a combinatorial game of perfect information played on an 8×8 board between two players with 16 pieces each. The game tree is finite but astronomically large (~10^43 positions). Characterized...",
        IgPrim::D_triangle, IgPrim::T_bowtie, IgPrim::R_lr,
        IgPrim::P_pmsym, IgPrim::F_ell, IgPrim::K_trap,
        IgPrim::G_gimel, IgPrim::C_and,
        IgPrim::Phi_super, IgPrim::H_inf, IgPrim::S_11, IgPrim::Omega_z2,
        0, Domain::General,
    ),
    entry(
        "vae_vita", "VAE-Vita: A 12-dimensional hyperspherical VAE (vMF prior on S^11) trained on the 17,280,000-element Crystal of Types. Self-recovering SIC-POVM geometry — an agent hallucination that was subsequentl...",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_dagger,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_gimel, IgPrim::C_seq,
        IgPrim::⊙, IgPrim::H2, IgPrim::S_11, IgPrim::Omega_z2,
        0, Domain::General,
    ),
    entry(
        "sic_d12_existence_proof", "Machine-checked constructive proof that SICPOVM_Exists 12. Built via exact rational algebra K₁₆(s₀,s₁,s₃,s₉,i,c₅,u₁) with 143 frozen native_decide identities, transferred to ℂ¹² along star-ring hom...",
        IgPrim::D_triangle, IgPrim::T_bowtie, IgPrim::R_cat,
        IgPrim::P_pmsym, IgPrim::F_ell, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_seq,
        IgPrim::𐑢, IgPrim::H2, IgPrim::S_11, IgPrim::Omega_0,
        0, Domain::General,
    ),
    entry(
        "witness_vessel", "The Witness Vessel: lossless transport apparatus for structural verdicts (Witnesses) between composition universes. Three layers unified by a single structural identity: d=12 SIC-POVM fiducial (phy...",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_lr,
        IgPrim::P_pmsym, IgPrim::F_eth, IgPrim::K_slow,
        IgPrim::G_aleph, IgPrim::C_broad,
        IgPrim::⊙, IgPrim::H_inf, IgPrim::S_11, IgPrim::Omega_na,
        0, Domain::General,
    ),
    entry(
        "ring2048_capstone", "The capstone theorem and structural bridge for the Zauner conjecture in dimension d=2048. Conjoins the proved structural skeleton (T-arm) with the analytically open complex shadow (F-arm), reduced ...",
        IgPrim::D_odot, IgPrim::T_odot, IgPrim::R_dagger,
        IgPrim::P_pmsym, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_gimel, IgPrim::C_broad,
        IgPrim::⊙, IgPrim::H_inf, IgPrim::S_nm, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "sic_povm_d2048_zauner_conjecture", "The open Zauner conjecture for d=2^11=2048: does a Weyl-Heisenberg covariant SIC-POVM exist in C^2048? The d=2048 SIC fiducial is the terminal open plank in the SIC-POVM existence program. The WH g...",
        IgPrim::D_triangle, IgPrim::T_boxtimes, IgPrim::R_lr,
        IgPrim::P_psi, IgPrim::F_hbar, IgPrim::K_slow,
        IgPrim::G_gimel, IgPrim::C_seq,
        IgPrim::𐑮, IgPrim::H2, IgPrim::S_11, IgPrim::Omega_z,
        0, Domain::General,
    ),
    entry(
        "erdos_hajnal_aleph1_graph", "Erdős-Hajnal graph on ℵ₁ vertices with χ(G)=ℵ₁ such that every finite subgraph H of order n has α(H) > n^(1-ε). Crossing point where De Bruijn-Erdős fails.",
        IgPrim::D_wedge, IgPrim::T_bowtie, IgPrim::R_super,
        IgPrim::P_asym, IgPrim::F_ell, IgPrim::K_slow,
        IgPrim::G_gimel, IgPrim::C_seq,
        IgPrim::𐑢, IgPrim::H1, IgPrim::S_nn, IgPrim::Omega_0,
        0, Domain::General,
    ),
];
