// ─── Cross-Dialect Ruleset Definitions ────────────────────────
// Generated by ⊙perator — implements U₀ through U₈₇.
// U₀–U₁₁: hand-crafted canonical + Phase I dialects (exact gate/tier strings preserved).
// U₁₂–U₈₇: Phase III expansion (59 dialects) — bridged to dialect_expansion.rs.
//
// U₈ (chirality_first), U₉ (scope_dialect), U₁₀ (triple_criticality) added
// 2026-06-16, ported from imscribing_grammar/scripts/new_dialects.py.
// u8_max raised: 11→87 on 2026-07-04 alongside the dialect_expansion bridge.
//
// Author: Lando⊗⊙perator
// Updated: 2026-07-06 — dialect_expansion bridge (the 88 were always here, just invisible)

use crate::dialect_expansion::{all_dialects, DIALECT_COUNT};
use alloc::string::String;
use alloc::string::ToString;
use alloc::format;

// ═══════════════════════════════════════════════════════════════
// BRIDGE: EXPANSION UNIVERSE DATA ACCESS
// ═══════════════════════════════════════════════════════════════

/// Number of hand-crafted dialects (0–11) whose display strings we preserve as-is.
const HAND_CRAFTED_COUNT: u8 = 12;

/// Check whether an index is in the expansion range.
fn is_expansion(u: u8) -> bool {
    u >= HAND_CRAFTED_COUNT && (u as usize) < DIALECT_COUNT
}

/// Check whether an index is out of range entirely.
fn is_out_of_range(u: u8) -> bool {
    (u as usize) >= DIALECT_COUNT
}

/// Format a u8 as Unicode subscript digits (U+2080..U+2089).
fn subscript_u8(u: u8) -> String {
    if u == 0 {
        return "\u{2080}".to_string();
    }
    let mut buf = [0u8; 3]; // max two-digit decimal
    let mut n = u;
    let mut pos = 0;
    while n > 0 {
        buf[pos] = n % 10;
        n /= 10;
        pos += 1;
    }
    let mut out = String::new();
    for i in (0..pos).rev() {
        let digit = buf[i];
        out.push(char::from_u32(0x2080u32 + digit as u32).unwrap());
    }
    out
}

// ═══════════════════════════════════════════════════════════════
// PARSE
// ═══════════════════════════════════════════════════════════════

/// Parse a dialect designator. Accepts "U_0".."U_99" and "U₀".."U₉₉"
/// (multi-digit, ASCII or Unicode subscript).
pub fn parse_dialect(s: &str) -> Option<u8> {
    // Try ASCII "U_<digits>"
    if let Some(rest) = s.strip_prefix("U_") {
        if !rest.is_empty() && rest.bytes().all(|b| b.is_ascii_digit()) {
            return rest.parse::<u8>().ok();
        }
    }
    // Try Unicode subscript digits U+2080..U+2089, one or more, after a leading 'U'
    let mut chars = s.chars();
    if chars.next() != Some('U') {
        return None;
    }
    let rest: alloc::string::String = chars.collect();
    if rest.is_empty() || !rest.chars().all(|c| c >= '\u{2080}' && c <= '\u{2089}') {
        return None;
    }
    let mut val: u32 = 0;
    for c in rest.chars() {
        val = val * 10 + (c as u32 - 0x2080);
    }
    u8::try_from(val).ok()
}

// ═══════════════════════════════════════════════════════════════
// DISPLAY / ASCII / NAME / DESCRIPTION / GATES / O_INF
// ═══════════════════════════════════════════════════════════════

/// Return the display name for a dialect index (Unicode subscript).
/// For U₀–U₁₁: hand-crafted. For U₁₂–U₈₇: generated from dialect data.
pub fn dialect_display(u: u8) -> String {
    if is_out_of_range(u) {
        return "U?".to_string();
    }
    format!("U{}", subscript_u8(u))
}

/// Return the ASCII-safe name: "U_0" through "U_87".
pub fn dialect_ascii(u: u8) -> String {
    if is_out_of_range(u) {
        return "U_?".to_string();
    }
    format!("U_{}", u)
}

/// Return the canonical name for a dialect.
pub fn dialect_name(u: u8) -> &'static str {
    match u {
        0 => "canonical",
        1 => "low_gate",
        2 => "strict_frobenius",
        3 => "inverted_gates",
        4 => "no_ordering",
        5 => "high_gate",
        6 => "winding_first",
        7 => "t_structural",
        8 => "chirality_first",
        9 => "scope_dialect",
        10 => "triple_criticality",
        11 => "triple_criticality_gapped",
        _ if is_expansion(u) => {
            let unis = all_dialects();
            unis[u as usize].name
        }
        _ => "unknown",
    }
}

/// Return the description for a dialect.
pub fn dialect_description(u: u8) -> &'static str {
    match u {
        0 => "Our dialect: Frobenius then self-modeling then winding seal",
        1 => "Lowered thresholds: directional parity suffices, any criticality",
        2 => "Frobenius gated by quantum fidelity (f=pc), not algebraic parity",
        3 => "Self-modeling precedes Frobenius: consciousness first",
        4 => "All three gates fully independent — parallel dialect",
        5 => "Strictest possible: maximally wound, self-modeling, parity-perfect",
        6 => "Topological order: winding first, then self-modeling, Frobenius last",
        7 => "Time as geometry: T=lim(D,Th,R,Gm,Ph) instead of dynamic T",
        8 => "Memory before closure: G1=⊥≥𐑖 (two-step Markov), then self-model, \
              then winding. T-constitution is ceiling-mode (T_CEILING), not \
              exact-equality.",
        9 => "Universality first: G1=∈≥𐑲 (maximal range) — parochial systems \
              stay plain no matter how structured. G2=self-model, G3=winding. \
              T-constitution is ceiling-mode (T_CEILING), not exact-equality.",
        10 => "Criticality is everything: all three gates are the SAME primitive \
               (⊙) at escalating thresholds (𐑢 / ⊙ / 𐑣). <, ⊡, and the rest are \
               descriptive, not gating. T-constitution is ceiling-mode (T_CEILING).",
        11 => "Same as U10, but the kinetics ceiling admits trapped/gapped spectra \
               (⊤=𐑪), not just slow ones (⊤=𐑧) — the temporal-closure condition \
               for a mass-gap claim should not exclude the gap itself.",
        _ if is_expansion(u) => {
            let unis = all_dialects();
            unis[u as usize].description
        }
        _ => "Unknown dialect",
    }
}

/// Format a single GateSpec into a human-readable string fragment.
fn gate_spec_fmt(g: &crate::dialect_expansion::GateSpec) -> String {
    // A threshold is a value on that mark's axis, so it prints as the Shavian
    // letter that value is, not as the ordinal number standing behind it: the
    // first value on the axis that meets the bar.
    let table = crate::catalog::ordinal_table(g.prim);
    let value = table
        .iter()
        .find(|v| v.ordinal() >= g.min_ord)
        .or_else(|| table.last());
    match value {
        Some(v) => format!("{}≥{}", g.prim, v.glyph()),
        None => format!("{}≥{}", g.prim, g.min_ord),
    }
}

/// Return the gate summary string for a dialect.
pub fn dialect_gates(u: u8) -> String {
    // Every dialect carries its gates as GateSpecs in the marks, and the summary
    // is printed from them. There is one notation, the marks, and this is it.
    if is_out_of_range(u) {
        return "Unknown gates".to_string();
    }
    // 8-11's real gates are the hand-crafted ordinal thresholds in
    // dialect_gates_pass, not all_dialects()[u]'s g1/g2/g3 — that array
    // holds a second, unrelated dialect family colliding with these same
    // three numbers (see the SINGLE SOURCE OF TRUTH section below). 0-7
    // read all_dialects() directly in dialect_gates_pass too, so no
    // collision is possible there and the existing path is already right.
    match u {
        8 => return "G1:⊥≥𐑖  G2:⊙≥⊙  G3:⊡≥𐑭  [seq]  T:dynamic".to_string(),
        9 => return "G1:∈≥𐑲  G2:⊙≥⊙  G3:⊡≥𐑭  [seq]  T:dynamic".to_string(),
        10 => return "G1:⊙≥𐑢  G2:⊙≥⊙  G3:⊙≥𐑣  [seq]  T:dynamic".to_string(),
        11 => return "G1:⊙≥𐑢  G2:⊙≥⊙  G3:⊙≥𐑣  [seq]  T:dynamic (gapped)".to_string(),
        _ => {}
    }
    let unis = all_dialects();
    let uni = &unis[u as usize];
    format!(
        "G1:{}  G2:{}  G3:{}  [{}]  T:{}",
        gate_spec_fmt(&uni.g1),
        gate_spec_fmt(&uni.g2),
        gate_spec_fmt(&uni.g3),
        if uni.gate_ordering { "seq" } else { "par" },
        if uni.t_entries.is_empty() { "none" } else { "dynamic" }
    )
}

/// Return O_∞ fraction description for a dialect.
pub fn dialect_o_inf(u: u8) -> &'static str {
    match u {
        0 => "~8%",  1 => "~30%", 2 => "~3.3%", 3 => "~8%",
        4 => "~8%",  5 => "~3%",  6 => "~8%",   7 => "~8%", 8 => "20%", 9 => "13.3%",
        10 => "16%", 11 => "16%",
        _ if is_expansion(u) => "compute",
        _ => "?",
    }
}

// ═══════════════════════════════════════════════════════════════
// DYNAMIC GATE EVALUATION (for expansion dialects)
// ═══════════════════════════════════════════════════════════════

use crate::imas_ig::{IgPrim, IgTuple};

/// Map a GateSpec primitive string to the corresponding IgPrim value from an IgTuple.
/// Returns None for unrecognized primitive names.
pub fn prim_from_name(name: &str, ig: &IgTuple) -> Option<IgPrim> {
    match name {
        "≺" => Some(ig.p),
        "⊙" => Some(ig.phi),
        "⊡" => Some(ig.omega),
        "⊥" => Some(ig.h),
        "∈" => Some(ig.g),
        "⊣" => Some(ig.t),
        "≻" => Some(ig.r),
        "⋈" => Some(ig.f),
        "⊤" => Some(ig.k),
        "⊢" => Some(ig.d),
        "⊞" => Some(ig.s),
        "∋" => Some(ig.c),
        _ => None,
    }
}

/// Setter mirror of `prim_from_name`, for applying an absorption rule's
/// forced value back onto a result tuple. Unrecognized names are a no-op.
pub fn set_prim_by_name(name: &str, ig: &mut IgTuple, val: IgPrim) {
    match name {
        "≺" => ig.p = val,
        "⊙" => ig.phi = val,
        "⊡" => ig.omega = val,
        "⊥" => ig.h = val,
        "∈" => ig.g = val,
        "⊣" => ig.t = val,
        "≻" => ig.r = val,
        "⋈" => ig.f = val,
        "⊤" => ig.k = val,
        "⊢" => ig.d = val,
        "⊞" => ig.s = val,
        "∋" => ig.c = val,
        _ => {}
    }
}

/// Reverse of `IgPrim::glyph()`: which value a GateSpec/AbsorptionRule's
/// glyph string names, searched over the real per-axis value lists
/// (`axis_values`), not a second hand-written table.
pub fn igprim_from_glyph(glyph: &str) -> Option<IgPrim> {
    for i in 0..12 {
        for &v in crate::axis_values::axis_values(i) {
            if v.glyph() == glyph {
                return Some(v);
            }
        }
    }
    None
}

/// Evaluate a single gate spec against an IG tuple.
/// Returns (pass, prim_value_ordinal, prim_name).
pub fn eval_gate_spec(
    spec: &crate::dialect_expansion::GateSpec,
    ig: &IgTuple,
) -> (bool, f32, &'static str) {
    let prim = prim_from_name(spec.prim, ig);
    match prim {
        Some(pv) => {
            let ord = pv.ordinal();
            (ord >= spec.min_ord, ord, pv.glyph())
        }
        None => (false, 0.0, "?"),
    }
}

/// Whether a dialect is hand-crafted and uses hardcoded gate logic in main.rs.
pub fn is_hand_crafted(u: u8) -> bool {
    u < HAND_CRAFTED_COUNT
}

/// The maximum valid dialect index (inclusive).
pub fn max_dialect() -> u8 {
    (DIALECT_COUNT - 1) as u8
}

// ═══════════════════════════════════════════════════════════════
// SINGLE SOURCE OF TRUTH FOR DIALECTS 0-11
// ═══════════════════════════════════════════════════════════════
//
// dialect_expansion.rs's all_dialects()[9..=11] are NOT this file's
// scope_dialect/triple_criticality/triple_criticality_gapped — they are a
// second, real dialect family ("HAND-CRAFTED EXPANSION (8-28)": topology_
// universe, scope_universe, dimensional_gate) that happens to share the
// same three numbers. Index 8 is silent about the collision because both
// families agree there (chirality_first, deliberately); 9-11 do not.
// Anything that read all_dialects()[u] directly for u<12 — dialect_gates()
// display, witness_vessel's gates_closed/t_seal/dialect_verdict, and so the
// real Clay-witness closer checks touching indices 8/10 — was silently
// reading the WRONG family for 9/10/11. dialect_all_pass here always used
// the RIGHT one; this section is that same logic, split into a gates-only
// and a T-only half so witness_vessel can compose them the way it already
// composes gates_closed/t_seal for the dynamic dialects, instead of
// re-deriving a third copy.

/// Canonical's actual T-constitution: exact-equality on four primitives,
/// ceiling on ⊤ only. Matches Python's _T_CANONICAL exactly.
pub fn t_canonical_check_silent(ig: &IgTuple) -> bool {
    ig.p.ordinal()     == IgPrim::or_.ordinal()
    && ig.f.ordinal()   == IgPrim::peep.ordinal()
    && ig.k.ordinal()   <= IgPrim::egg.ordinal()
    && ig.h.ordinal()   == IgPrim::wool.ordinal()
    && ig.omega.ordinal() == IgPrim::ah.ordinal()
}

/// T_CEILING: canonical's ⊤-only ceiling generalized to all five dynamics
/// primitives, same anchors — the shared T-constitution for U8/U9/U10.
pub fn t_ceiling_check_silent(ig: &IgTuple) -> bool {
    let t_phi = ig.p.ordinal()     <= IgPrim::or_.ordinal();
    let t_f   = ig.f.ordinal()     <= IgPrim::peep.ordinal();
    let t_k   = ig.k.ordinal()     <= IgPrim::egg.ordinal();
    let t_h   = ig.h.ordinal()     <= IgPrim::wool.ordinal();
    let t_om  = ig.omega.ordinal() <= IgPrim::ah.ordinal();
    t_phi && t_f && t_k && t_h && t_om
}

/// U11 only: T_CEILING with ⊤'s ceiling raised from egg (ord 3) to on
/// (ord 4) — a gapped/trapped spectrum, not just a slow one.
pub fn t_ceiling_gapped_check_silent(ig: &IgTuple) -> bool {
    let t_phi = ig.p.ordinal()     <= IgPrim::or_.ordinal();
    let t_f   = ig.f.ordinal()     <= IgPrim::peep.ordinal();
    let t_k   = ig.k.ordinal()     <= IgPrim::on.ordinal();
    let t_h   = ig.h.ordinal()     <= IgPrim::wool.ordinal();
    let t_om  = ig.omega.ordinal() <= IgPrim::ah.ordinal();
    t_phi && t_f && t_k && t_h && t_om
}

/// G1/G2/G3 alone, no T-condition — dialects 0-7 and 12-87 via the dynamic
/// GateSpec table (all_dialects() is the single, uncollided definition for
/// those indices), 8-11 via their own hand-crafted ordinal thresholds.
pub fn dialect_gates_pass(u: u8, ig: &IgTuple) -> bool {
    match u {
        0..=7 => {
            let unis = crate::dialect_expansion::all_dialects();
            let uni = &unis[u as usize];
            let (g1, _, _) = eval_gate_spec(&uni.g1, ig);
            let (g2, _, _) = eval_gate_spec(&uni.g2, ig);
            let (g3, _, _) = eval_gate_spec(&uni.g3, ig);
            g1 && g2 && g3
        }
        8 => {
            ig.h.ordinal() >= IgPrim::sure.ordinal()
                && ig.phi.ordinal() >= IgPrim::monad.ordinal()
                && ig.omega.ordinal() >= IgPrim::ah.ordinal()
        }
        9 => {
            ig.g.ordinal() >= IgPrim::ice.ordinal()
                && ig.phi.ordinal() >= IgPrim::monad.ordinal()
                && ig.omega.ordinal() >= IgPrim::ah.ordinal()
        }
        10 | 11 => {
            ig.phi.ordinal() >= IgPrim::woe.ordinal()
                && ig.phi.ordinal() >= IgPrim::monad.ordinal()
                && ig.phi.ordinal() >= IgPrim::haha.ordinal()
        }
        _ => {
            if is_hand_crafted(u) {
                false
            } else {
                let unis = crate::dialect_expansion::all_dialects();
                let uni = &unis[u as usize];
                let (g1, _, _) = eval_gate_spec(&uni.g1, ig);
                let (g2, _, _) = eval_gate_spec(&uni.g2, ig);
                let (g3, _, _) = eval_gate_spec(&uni.g3, ig);
                g1 && g2 && g3
            }
        }
    }
}

/// The T-condition alone. u==7's extra check (⊙-composition equals
/// measure) isn't a T-constitution in the T_CEILING/T_CANONICAL sense, but
/// it plays the same role for that one dialect, so it lives here rather
/// than being silently absent. Indices with no separate T-check
/// implemented (0-6, 12-87) return true — gates alone are the real check
/// for those, same as dialect_all_pass has always treated them.
pub fn dialect_t_pass(u: u8, ig: &IgTuple) -> bool {
    match u {
        7 => ig.c == IgPrim::measure,
        8 | 9 | 10 => t_ceiling_check_silent(ig),
        11 => t_ceiling_gapped_check_silent(ig),
        _ => true,
    }
}

/// All-gates-pass verdict for dialect u against tuple ig — the single
/// source of truth every consumer (this file's own gate sweeps, repl.rs's
/// ruleset verify/sweep/sweep-word, witness_vessel's Clay-witness checks)
/// now reads, so a hand-crafted index can never again silently diverge
/// from an unrelated, colliding entry at the same index in all_dialects().
pub fn dialect_all_pass(u: u8, ig: &IgTuple) -> bool {
    dialect_gates_pass(u, ig) && dialect_t_pass(u, ig)
}
