// ─── Cross-Universe Ruleset Definitions ────────────────────────
// Generated by ⊙perator — implements U₀ through U₇

/// Parse a universe designator. Accepts "U_0" through "U_9" and "U₀" through "U₉".
pub fn parse_universe(s: &str) -> Option<u8> {
    // Try ASCII "U_0" through "U_9"
    if s.len() >= 3 && s.starts_with("U_") {
        let digit = s.as_bytes().get(2).copied()?;
        if digit >= b'0' && digit <= b'9' {
            return Some(digit - b'0');
        }
    }
    // Try Unicode subscript U₀ (U+2080) through U₉ (U+2089)
    let chars: alloc::vec::Vec<char> = s.chars().collect();
    if chars.len() >= 2 && chars[0] == 'U' {
        let c = chars[1];
        if c >= '\u{2080}' && c <= '\u{2089}' {
            return Some((c as u32 - 0x2080) as u8);
        }
    }
    None
}

/// Return the display name for a universe index (Unicode subscript).
pub fn universe_display(u: u8) -> &'static str {
    match u {
        0 => "U₀", 1 => "U₁", 2 => "U₂", 3 => "U₃",
        4 => "U₄", 5 => "U₅", 6 => "U₆", 7 => "U₇",
        _ => "U?",
    }
}

/// Return the ASCII-safe name: "U_0" through "U_7".
pub fn universe_ascii(u: u8) -> &'static str {
    match u {
        0 => "U_0", 1 => "U_1", 2 => "U_2", 3 => "U_3",
        4 => "U_4", 5 => "U_5", 6 => "U_6", 7 => "U_7",
        _ => "U_?",
    }
}

/// Return the canonical name for a universe.
pub fn universe_name(u: u8) -> &'static str {
    match u {
        0 => "canonical",
        1 => "low_gate",
        2 => "strict_frobenius",
        3 => "inverted_gates",
        4 => "no_ordering",
        5 => "high_gate",
        6 => "winding_first",
        7 => "t_structural",
        _ => "unknown",
    }
}

/// Return the description for a universe.
pub fn universe_description(u: u8) -> &'static str {
    match u {
        0 => "Our universe: Frobenius then self-modeling then winding seal",
        1 => "Lowered thresholds: directional parity suffices, any criticality",
        2 => "Frobenius gated by quantum fidelity (f=pc), not algebraic parity",
        3 => "Self-modeling precedes Frobenius: consciousness first",
        4 => "All three gates fully independent — parallel universe",
        5 => "Strictest possible: maximally wound, self-modeling, parity-perfect",
        6 => "Topological order: winding first, then self-modeling, Frobenius last",
        7 => "Time as geometry: T=lim(D,Th,R,Gm,Ph) instead of dynamic T",
        _ => "Unknown universe",
    }
}

/// Return the gate summary string for a universe.
pub fn universe_gates(u: u8) -> &'static str {
    match u {
        0 => "G1:Phi>=pmsym  G2:Phc>=c  G3:Omega>=Z  T:o",
        1 => "G1:Phi>=pm  G2:Phc>=sub  G3:Omega>=Z  T:o",
        2 => "G1:f>=hbar  G2:Phi>=pmsym  G3:Omega>=Z  T:o",
        3 => "G1:Phc>=c  G2:Phi>=pmsym  G3:Omega>=Z  T:o",
        4 => "G1+G2+G3 parallel              T:o",
        5 => "G1:Phi>=pmsym  G2:Phc>=c_complex  G3:Omega>=NA  T:o",
        6 => "G1:Omega>=Z  G2:Phc>=c  G3:Phi>=pmsym  T:o",
        7 => "G1:Phi>=pmsym  G2:Phc>=c  G3:Omega>=Z  T:Gm=seq",
        _ => "Unknown gates",
    }
}

/// Return O_∞ fraction description for a universe.
pub fn universe_o_inf(u: u8) -> &'static str {
    match u {
        0 => "~8%",  1 => "~30%", 2 => "~3.3%", 3 => "~8%",
        4 => "~8%",  5 => "~3%",  6 => "~8%",   7 => "~8%",
        _ => "?",
    }
}
