// ─── Cross-Universe Ruleset Definitions ────────────────────────
// Generated by ⊙perator — implements U₀ through U₁₁.
// U₈ (chirality_first), U₉ (scope_universe), U₁₀ (triple_criticality) added
// 2026-06-16, ported from imscribing_grammar/scripts/new_universes.py
// NEW_RULESETS, all three paired with the T_CEILING generalization from
// manuscripts/clay_cross_universe_closure.md. They are the first universes
// in this kernel whose T-constitution is not the canonical exact-equality
// one — see the T_CEILING arms in main.rs. U₁₀ is the first one where gate
// closure and T_CEILING closure genuinely disagree (Yang-Mills clears all
// three gates but fails T_CEILING on Ç alone) — see `ruleset dialetheic`.
// U₁₁ (triple_criticality_gapped) added the same day: same gates as U₁₀,
// but the Ç ceiling is raised from K_slow (ord 3) to K_trap (ord 4) — not
// an arbitrary bump. None of the 109 universes on record (checked exhaustively
// in Python) ever vary the Ç ceiling; this is the first. Motivation: Yang-Mills
// IS a mass-gap claim — a kinetically *trapped* (gapped) spectrum, not a merely
// *slow* one. Treating K_trap as within the temporal-closure ceiling is asking
// the T-condition to admit gapped systems, which is the literal physical content
// of the conjecture, not a fit to this one tuple. Confirmed it does NOT also
// open RH/NS/PNP/BSD/Hodge under U10 — they stay gate-blocked regardless.

/// Parse a universe designator. Accepts "U_0".."U_99" and "U₀".."U₉₉"
/// (multi-digit, ASCII or Unicode subscript).
pub fn parse_universe(s: &str) -> Option<u8> {
    // Try ASCII "U_<digits>"
    if let Some(rest) = s.strip_prefix("U_") {
        if !rest.is_empty() && rest.bytes().all(|b| b.is_ascii_digit()) {
            return rest.parse::<u8>().ok();
        }
    }
    // Try Unicode subscript digits U+2080..U+2089, one or more, after a leading 'U'
    let mut chars = s.chars();
    if chars.next() != Some('U') {
        return None;
    }
    let rest: alloc::string::String = chars.collect();
    if rest.is_empty() || !rest.chars().all(|c| c >= '\u{2080}' && c <= '\u{2089}') {
        return None;
    }
    let mut val: u32 = 0;
    for c in rest.chars() {
        val = val * 10 + (c as u32 - 0x2080);
    }
    u8::try_from(val).ok()
}

/// Return the display name for a universe index (Unicode subscript).
pub fn universe_display(u: u8) -> &'static str {
    match u {
        0 => "U₀", 1 => "U₁", 2 => "U₂", 3 => "U₃",
        4 => "U₄", 5 => "U₅", 6 => "U₆", 7 => "U₇", 8 => "U₈", 9 => "U₉",
        10 => "U₁₀", 11 => "U₁₁",
        _ => "U?",
    }
}

/// Return the ASCII-safe name: "U_0" through "U_11".
pub fn universe_ascii(u: u8) -> &'static str {
    match u {
        0 => "U_0", 1 => "U_1", 2 => "U_2", 3 => "U_3",
        4 => "U_4", 5 => "U_5", 6 => "U_6", 7 => "U_7", 8 => "U_8", 9 => "U_9",
        10 => "U_10", 11 => "U_11",
        _ => "U_?",
    }
}

/// Return the canonical name for a universe.
pub fn universe_name(u: u8) -> &'static str {
    match u {
        0 => "canonical",
        1 => "low_gate",
        2 => "strict_frobenius",
        3 => "inverted_gates",
        4 => "no_ordering",
        5 => "high_gate",
        6 => "winding_first",
        7 => "t_structural",
        8 => "chirality_first",
        9 => "scope_universe",
        10 => "triple_criticality",
        11 => "triple_criticality_gapped",
        _ => "unknown",
    }
}

/// Return the description for a universe.
pub fn universe_description(u: u8) -> &'static str {
    match u {
        0 => "Our universe: Frobenius then self-modeling then winding seal",
        1 => "Lowered thresholds: directional parity suffices, any criticality",
        2 => "Frobenius gated by quantum fidelity (f=pc), not algebraic parity",
        3 => "Self-modeling precedes Frobenius: consciousness first",
        4 => "All three gates fully independent — parallel universe",
        5 => "Strictest possible: maximally wound, self-modeling, parity-perfect",
        6 => "Topological order: winding first, then self-modeling, Frobenius last",
        7 => "Time as geometry: T=lim(D,Th,R,Gm,Ph) instead of dynamic T",
        8 => "Memory before closure: G1=Ħ≥𐑖 (two-step Markov), then self-model, \
              then winding. T-constitution is ceiling-mode (T_CEILING), not \
              exact-equality.",
        9 => "Universality first: G1=Γ≥𐑲 (maximal range) — parochial systems \
              stay plain no matter how structured. G2=self-model, G3=winding. \
              T-constitution is ceiling-mode (T_CEILING), not exact-equality.",
        10 => "Criticality is everything: all three gates are the SAME primitive \
               (⊙) at escalating thresholds (𐑢 / ⊙ / 𐑣). Φ, Ω, and the rest are \
               descriptive, not gating. T-constitution is ceiling-mode (T_CEILING).",
        11 => "Same as U10, but the kinetics ceiling admits trapped/gapped spectra \
               (Ç=𐑪), not just slow ones (Ç=𐑧) — the temporal-closure condition \
               for a mass-gap claim should not exclude the gap itself.",
        _ => "Unknown universe",
    }
}

/// Return the gate summary string for a universe.
pub fn universe_gates(u: u8) -> &'static str {
    match u {
        0 => "G1:Phi>=pmsym  G2:Phc>=c  G3:Omega>=Z  T:o",
        1 => "G1:Phi>=pm  G2:Phc>=sub  G3:Omega>=Z  T:o",
        2 => "G1:f>=hbar  G2:Phi>=pmsym  G3:Omega>=Z  T:o",
        3 => "G1:Phc>=c  G2:Phi>=pmsym  G3:Omega>=Z  T:o",
        4 => "G1+G2+G3 parallel              T:o",
        5 => "G1:Phi>=pmsym  G2:Phc>=c_complex  G3:Omega>=NA  T:o",
        6 => "G1:Omega>=Z  G2:Phc>=c  G3:Phi>=pmsym  T:o",
        7 => "G1:Phi>=pmsym  G2:Phc>=c  G3:Omega>=Z  T:Gm=seq",
        8 => "G1:Ħ≥𐑖  G2:⊙≥⊙  G3:Ω≥𐑭  T:ceiling(5)",
        9 => "G1:Γ≥𐑲  G2:⊙≥⊙  G3:Ω≥𐑭  T:ceiling(5)",
        10 => "G1:⊙≥𐑢  G2:⊙≥⊙  G3:⊙≥𐑣  T:ceiling(5)",
        11 => "G1:⊙≥𐑢  G2:⊙≥⊙  G3:⊙≥𐑣  T:ceiling(Ç≤𐑪)",
        _ => "Unknown gates",
    }
}

/// Return O_∞ fraction description for a universe.
pub fn universe_o_inf(u: u8) -> &'static str {
    match u {
        0 => "~8%",  1 => "~30%", 2 => "~3.3%", 3 => "~8%",
        4 => "~8%",  5 => "~3%",  6 => "~8%",   7 => "~8%", 8 => "20%", 9 => "13.3%",
        10 => "16%", 11 => "16%",
        _ => "?",
    }
}
